Repository vmware-tanzu/vm-operator, pull requests merged in 2023-07, with the labels that each got.

#168 :seedling: Only watch Create and Delete events for VMClass when reconcile VM
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_unit_test.go
Labels: size/M, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#167 ✨ Adds new condition to VirtualMachine to the expose state of metadata+userdata
  api/v1alpha1/condition_consts.go
  api/v1alpha2/virtualmachine_types.go
  go.mod
  go.sum
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#171 🌱 Consumes upstream image-registry-operator-api module
  Makefile
  config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitemimportrequests.yaml
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/utils/test_utils.go
  controllers/contentlibrary/utils/utils.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  external/image-registry/api/v1alpha1/condition_constants.go
  external/image-registry/api/v1alpha1/condition_types.go
  external/image-registry/api/v1alpha1/contentlibrary_types.go
  external/image-registry/api/v1alpha1/contentlibraryitem_types.go
  external/image-registry/api/v1alpha1/groupversion_info.go
  external/image-registry/api/v1alpha1/types.go
  external/image-registry/api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/context/clustercontentlibraryitem_context.go
  pkg/context/contentlibraryitem_context.go
  pkg/context/virtualmachinepublishrequest_context.go
  pkg/manager/manager.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/providers/vsphere/virtualmachine/publish.go
  pkg/vmprovider/providers/vsphere/virtualmachine/publish_test.go
  pkg/vmprovider/providers/vsphere/vmprovider.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  test/builder/fake.go
  test/builder/util.go
  webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator_unit_test.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#176 Revert "Adds new condition to expose state of guestinfo"
  api/v1alpha1/condition_consts.go
  api/v1alpha2/virtualmachine_types.go
  go.mod
  go.sum
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#175 :book: Add vappconfig.md doc
  docs/concepts/workloads/guest.md
  docs/tutorials/deploy-vm/vappconfig.md
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#172 Add v1a2 webhooks
  .golangci.yml
  test/builder/fake.go
  test/builder/utila2.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/helpers.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_suite_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/webhooks.go
  webhooks/virtualmachine/webhooks.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_intg_test.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_suite_test.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_unit_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_intg_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_suite_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_unit_test.go
  webhooks/virtualmachineclass/v1alpha2/webhooks.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_suite_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_unit_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/webhooks.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_intg_test.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_suite_test.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_unit_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_intg_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_suite_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_unit_test.go
  webhooks/virtualmachineservice/v1alpha2/webhooks.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_intg_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_suite_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_unit_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/webhooks.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#180 Do not allocate NodePorts for VirtualMachineService Services
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go
Labels: size/XS, cla-not-required

#182 Revert "Only watch Create and Delete events for VMClass when reconcil…
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_unit_test.go
Labels: size/M, cla-not-required

#173 Update v1a2 VirtualMachine types
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
Labels: size/M, cla-not-required

#174 Import v1a2 pkg changes
  api/v1alpha2/condition_consts.go
  pkg/conditions2/conditions_suite_test.go
  pkg/conditions2/getter.go
  pkg/conditions2/getter_test.go
  pkg/conditions2/matcher.go
  pkg/conditions2/matcher_test.go
  pkg/conditions2/merge.go
  pkg/conditions2/merge_strategies.go
  pkg/conditions2/merge_strategies_test.go
  pkg/conditions2/merge_test.go
  pkg/conditions2/patch.go
  pkg/conditions2/patch_test.go
  pkg/conditions2/setter.go
  pkg/conditions2/setter_test.go
  pkg/conditions2/unstructured.go
  pkg/conditions2/unstructured_test.go
  pkg/conditions2/utils.go
  pkg/patch2/options.go
  pkg/patch2/patch.go
  pkg/patch2/patch_test.go
  pkg/patch2/suite_test.go
  pkg/patch2/utils.go
  pkg/patch2/utils_test.go
  pkg/prober2/context/probe_context.go
  pkg/prober2/fake/fake_prober_manager.go
  pkg/prober2/fake/probe/fake_probe.go
  pkg/prober2/fake/worker/fake_prober_worker.go
  pkg/prober2/probe/heartbeat.go
  pkg/prober2/probe/heartbeat_test.go
  pkg/prober2/probe/probe.go
  pkg/prober2/probe/tcp.go
  pkg/prober2/probe/tcp_test.go
  pkg/prober2/prober_manager.go
  pkg/prober2/prober_manager_test.go
  pkg/prober2/worker/prober_worker.go
  pkg/prober2/worker/readiness_worker.go
  pkg/prober2/worker/readiness_worker_test.go
  pkg/vmprovider/fake/fake_vm_provider_a2.go
  pkg/vmprovider/interface_a2.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#183 📖 Consolidate content in the Cloud-Init and Deploy VM docs
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/deploy-vm/cloudinit.md
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#186 📖 Add callout to address incomplete Sysprep state issue
  docs/concepts/workloads/guest.md
Labels: size/XS, cla-not-required

#187 Add relative binary path to -only .PHONY targets
  Makefile
Labels: size/XS, cla-not-required

#188 🌱 Rename SelectVGPU taking BackingType into account
  pkg/util/devices.go
  pkg/util/devices_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
Labels: size/M, cla-not-required

#184 :sparkles: Ensure lossless conversion of VirtualMachineClass new fields
  api/utilconversion/conversion.go
  api/utilconversion/conversion_fuzz.go
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachineclass_conversion.go
Labels: size/L, testing-needed-e2e-fast, cla-not-required

#189 📖 Documentation for VM's resources (CPU, Memory, Storage and Network)
  docs/concepts/workloads/vm.md
Labels: size/M, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required
