Repository vmware-tanzu/vm-operator, pull requests merged in 2023-04, with the labels that each got.

#134 Update kind k8s version to 1.24
  Makefile
  hack/deploy-local.sh
Labels: size/XS, cla-not-required

#135 Sync v1a1 VirtualMachineImage changes to v1a2
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachineimage_types.go
Labels: size/M, cla-not-required

#137 Fix VirtualMachineService selectorless behavior
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller_intg_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#139 Fix up computeCPUMinFrequency for the createVM path and add some CPU/Mem Reservation tests
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#136 Update template to support Sysprep guest customization
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/virtualmachinetempl_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/guest.md
  docs/concepts/workloads/vm.md
  docs/ref/proj/docs.md
  docs/start/quick.md
  mkdocs.yml
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/network/network_provider.go
  pkg/vmprovider/providers/vsphere/session/session_suite_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#141 Fix v1a2 VirtualMachineImage shortName typo
  api/v1alpha2/virtualmachineimage_types.go
Labels: size/XS, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required
