Repository vmware-tanzu/vm-operator, pull requests merged in 2023-08, with the labels that each got.

#197 🐛 Bump manager container memory limit
  config/wcp/vmoperator/cpu_resources_patch.yaml
Labels: size/XS, cla-not-required

#195 ✨ Make infra related controllers v1a2 aware
  controllers/infracluster/infracluster_controller.go
  controllers/infraprovider/infraprovider_controller.go
  pkg/context/controller_manager_context.go
Labels: size/M, cla-not-required

#203 ✨Generate v1a2 CRD and webhooks manifests
  Makefile
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/webhook/manifests.yaml
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#201 📖 Add troubleshooting readme and troubleshooting deploy vm
  .github/PULL_REQUEST_TEMPLATE.md
  docs/concepts/workloads/guest.md
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/troubleshooting/README.md
  docs/tutorials/troubleshooting/deploy-vm.md
  docs/tutorials/troubleshooting/ip-assignment.md
  docs/tutorials/troubleshooting/publish-vm.md
  mkdocs.yml
Labels: documentation, size/M, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#204 :seedling: Limit template rendering to only vAppConfig and Sysprep transport
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
Labels: size/XS, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#202 🐛 Better handle when CnsNodeVmAttachment unexpectedly already exists
  controllers/volume/v1alpha1/volume_controller.go
  controllers/volume/v1alpha1/volume_controller_unit_test.go
  controllers/volume/v1alpha2/volume_controller.go
  controllers/volume/v1alpha2/volume_controller_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#208 🌱 Remove v1a2 CRDs and webhooks on local kind environments based on v1alpha2 FSS
  hack/deploy-local.sh
Labels: size/XS, cla-not-required

#207 🐛 Adds event filter to incoming VirtualMachine objects only
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
Labels: size/M, cla-not-required

#206 ✨Enable v1a2 controller and webhook integration tests
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_suite_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_suite_test.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller_suite_test.go
  controllers/virtualmachineclass/v1alpha2/virtualmachineclass_controller_suite_test.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_suite_test.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_suite_test.go
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_suite_test.go
  controllers/volume/v1alpha2/volume_controller_suite_test.go
  pkg/manager/manager.go
  test/builder/test_suite.go
  test/builder/util.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_suite_test.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_suite_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_suite_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_suite_test.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_suite_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_suite_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_suite_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#209 ✨Add PublicKey and Response fields to v1a2 VirtualMachineWebConsoleRequest CRD
  api/v1alpha2/virtualmachinewebconsolerequest_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
Labels: size/S, cla-not-required
