Repository vmware-tanzu/vm-operator, pull requests merged in 2023-09, with the labels that each got.

#218 ✨ Add v1a2 webconsole request controllers
  config/rbac/role.yaml
  controllers/virtualmachinewebconsolerequest/controllers.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_suite_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_unit_test.go
  pkg/context/webconsolerequest_context.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#211 :bug: fix bug when using CloudInit without userdata to bootstrap VM
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#213 ✨ Persist VM's kubernetes and bootstrap data in ExtraConfig
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha1/virtualmachine_controller_unit_test.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller_unit_test.go
  pkg/lib/env.go
  pkg/util/enc.go
  pkg/util/enc_test.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/fake/fake_vm_provider_a2.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/interface_a2.go
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_util.go
  pkg/vmprovider/providers/vsphere/session/session_util_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#225 :sparkles: Update GoVmomi to 8.0U1c
  go.mod
  go.sum
Labels: size/S, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#222 🌱 Bump up controller-runtime to v0.15.0
  controllers/infracluster/infracluster_controller.go
  controllers/providerconfigmap/provider_configmap_controller.go
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  controllers/virtualmachinepublishrequest/v1alpha1/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/v1alpha1/virtualmachinepublishrequest_controller_unit_test.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_unit_test.go
  controllers/virtualmachineservice/v1alpha1/virtualmachineservice_controller.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller.go
  controllers/volume/v1alpha1/volume_controller.go
  controllers/volume/v1alpha2/volume_controller.go
  go.mod
  go.sum
  main.go
  pkg/builder/mutating_webhook.go
  pkg/builder/validating_webhook.go
  pkg/manager/cache.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/vmprovider/providers/vsphere/network/network_provider.go
  pkg/vmprovider/providers/vsphere/network/network_provider_test.go
  test/builder/fake.go
  test/builder/test_suite.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#223 ✨ Support VM deployment from image status (friendly) name
  config/rbac/role.yaml
  controllers/contentlibrary/v1alpha1/utils/utils.go
  pkg/lib/env.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#227 🐛 Do not fail PR when the testing-done-e2e-full label presents
  .github/workflows/testing-needed.yml
Labels: size/S, cla-not-required

#220 :book: Add troubleshooting page for ip assignment issue
  docs/tutorials/troubleshooting/ip-assignment.md
Labels: documentation, size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#228 :seedling: Bump up min go version to 1.20
  .github/workflows/ci.yml
  Dockerfile
  go.mod
  main.go
  pkg/util/enc_test.go
  test/builder/util.go
Labels: size/S, cla-not-required

#226 ✨ Include the controller-runtime conversion webhook patches for v1a2 and update v1a1 webhook names
  config/crd/kustomization.yaml
  config/webhook/manifests.yaml
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_suite_test.go
  webhooks/virtualmachineclass/v1alpha1/mutation/virtualmachineclass_mutator.go
  webhooks/virtualmachineclass/v1alpha1/mutation/virtualmachineclass_mutator_suite_test.go
  webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator.go
  webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator_suite_test.go
  webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator_suite_test.go
  webhooks/virtualmachineservice/v1alpha1/mutation/virtualmachineservice_mutator.go
  webhooks/virtualmachineservice/v1alpha1/mutation/virtualmachineservice_mutator_suite_test.go
  webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator.go
  webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator_suite_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha1/mutation/virtualmachinesetresourcepolicy_mutator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha1/mutation/virtualmachinesetresourcepolicy_mutator_suite_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator_suite_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator_suite_test.go
Labels: size/M, cla-not-required

#230 :sparkles: Update GoVmomi to 8.0U2
  go.mod
  go.sum
Labels: size/XS, testing-done-e2e-fast

#232 ✨ Remove content library fields from VirtualMachineImage printer columns
  api/v1alpha1/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
Labels: size/S, cla-not-required

#233 :sparkles: Markdown updates / VM image documentation
  docs/concepts/images/vm-image.md
  docs/requirements.txt
  docs/www/themes/material/main.html
  mkdocs.yml
Labels: documentation, size/M, cla-not-required

#234 ✨ Make v1a1 webconsole controller v1a2 VMProvider aware
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_suite_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#229 ✨ Persist VM disk path and type info in ExtraConfig
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-full, cla-not-required
