Repository vmware-tanzu/vm-operator, pull requests merged in 2023-05, with the labels that each got.

#142 Various v1a2 VirtualMachine CRD updates
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/virtualmachine_storage_types.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachinetempl_types.go
  api/v1alpha2/zz_generated.deepcopy.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#143 Initial pass at v1a2 VirtualMachine CRD doc updates
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/virtualmachine_readiness_types.go
  api/v1alpha2/virtualmachine_types.go
Labels: size/M, cla-not-required

#144 Consume latest image-registry API changes
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraryitems.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitems.yaml
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/utils/test_utils.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  external/image-registry/api/v1alpha1/clustercontentlibrary_types.go
  external/image-registry/api/v1alpha1/clustercontentlibraryitem_types.go
  external/image-registry/api/v1alpha1/condition_constants.go
  external/image-registry/api/v1alpha1/contentlibrary_types.go
  external/image-registry/api/v1alpha1/contentlibraryitem_types.go
  external/image-registry/api/v1alpha1/groupversion_info.go
  external/image-registry/api/v1alpha1/types.go
  external/image-registry/api/v1alpha1/zz_generated.deepcopy.go
  pkg/vmprovider/providers/vsphere/virtualmachine/publish.go
  pkg/vmprovider/providers/vsphere/vmprovider.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  test/builder/util.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#149 📖 Update v1alpha2 Sysprep API related comments
  api/v1alpha2/sysprep/sysprep.go
  api/v1alpha2/virtualmachine_network_types.go
Labels: size/S, cla-not-required

#150 🌱 Updates the minimum hardware version for persistent volumes
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/providers/vsphere/constants/constants.go
Labels: size/XS, testing-needed-e2e-fast, cla-not-required

#153 🌱 Separate WCP_Namespaced_Class_And_Windows_Support into two FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  pkg/lib/env.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required
