Repository vmware-tanzu/vm-operator, pull requests merged in 2023-02, with the labels that each got.

#55 Fix class ConfigSpec NIC with NSX-T network
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/S

#57 Do not consider hardware spec and RLS settings in Update path
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#59 Fix nil map in UpdateVirtualMachine
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
Labels: size/XS

#58 Only add PCI passthrough devices from ConfigSpec if FSS is enabled
  pkg/util/devices.go
  pkg/util/devices_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere/virtualmachine/devices.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#61 Add proxy address in web console request
  api/v1alpha1/webconsolerequest_types.go
  config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
  controllers/webconsolerequest/webconsolerequest_controller.go
  controllers/webconsolerequest/webconsolerequest_intg_test.go
  controllers/webconsolerequest/webconsolerequest_unit_test.go
  docs/apis/v1alpha1.md
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#31 Followup changes for VirtualMachinePublishRequest conditions.
  api/v1alpha1/condition_consts.go
  api/v1alpha1/virtualmachinepublishrequest_types.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  go.mod
  go.sum
  pkg/context/virtualmachinepublishrequest_context.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_create.go
  pkg/vmprovider/providers/vsphere/virtualmachine/publish.go
  pkg/vmprovider/providers/vsphere/vmprovider.go
  test/builder/util.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_unit_test.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full

#47 Implement caching for download of virtual machine images
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/utils/test_utils.go
  pkg/util/cache.go
  pkg/util/cache_test.go
  pkg/util/lock_pool.go
  pkg/util/lock_pool_test.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider.go
  pkg/vmprovider/providers/vsphere/vmprovider_test.go
  pkg/vmprovider/providers/vsphere/vsphere_suite_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full

#60 Convert network provider tests to vcsim test context
  pkg/vmprovider/providers/vsphere/network/network_provider.go
  pkg/vmprovider/providers/vsphere/network/network_provider_test.go
  pkg/vmprovider/providers/vsphere/network/network_suite_test.go
  test/builder/vcsim_test_context.go
Labels: size/L, testing-needed-e2e-fast

#67 Set default envtest asset directory when not provided
  test/builder/test_suite.go
Labels: size/XS

#64 Fix race in VirtualMachineSetResourcePolicy integration test
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_intg_test.go
Labels: size/XS

#65 Stop creating TKG content source related resources.
  controllers/controllers.go
Labels: size/XS

#66 Fix NSX-T LogicalSwitchUUID to DVPG lookup
  pkg/vmprovider/providers/vsphere/network/network_provider.go
  pkg/vmprovider/providers/vsphere/network/network_provider_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast
