Repository vmware-tanzu/vm-operator, pull requests merged in 2023-11, with the labels that each got.

#259 ✨ Remove the v1a2 Network top-level interface-related fields
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  test/builder/utila2.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#262 :sparkles: Add validations for Networkspec with its supported Bootstrap and unit tests
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#264 🌱 Move VM backup/restore related constants to API module
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/constants/constants.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#265 🐛 Revert "Mark v1a2 VirtualMachineClass as namespace scoped"
  api/v1alpha2/virtualmachineclass_types.go
Labels: size/XS, cla-not-required

#266 🐛 Add missing omitempty on CloudConfig User Passwd field
  api/v1alpha2/cloudinit/cloudconfig.go
Labels: size/XS, cla-not-required

#263 ✨ Version conversion support for v1a2 BootDiskCapacity
  api/v1alpha1/virtualmachine_conversion.go
Labels: size/M, cla-not-required

#267 🌱 Removing duplicate error logger in VM controller
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
Labels: size/XS, cla-not-required

#268 ✨ Make VM Spec BootDiskCapacity field a pointer
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  pkg/vmprovider/providers/vsphere2/session/session_vm.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create_clone.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
Labels: size/M, cla-not-required

#270 🐛 Remove updates to DeviceGroups
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#269 :seedling:Add validation on Bootstrap vAppConfig Properties
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#205 ✨ Adds minimum hardware version to VirtualMachine CRD
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/hardware_version.go
  pkg/util/hardware_version_test.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_status.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  test/builder/util.go
  test/builder/utila2.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#274 :seedling: Bump up go version from 1.21.3 to 1.21.4
  .github/workflows/ci.yml
  Dockerfile
Labels: size/XS, cla-not-required

#271 ✨ Make CloudInit and Sysprep raw and inlined fields pointers
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_provider.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#275 🐛 v1a2 VM mutation webhook updates
  pkg/builder/mutating_webhook.go
  pkg/context/webhook_request_context.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#272 Fix envtest assets directory
  test/builder/test_suite.go
Labels: size/XS, cla-not-required

#273 🌱 Remove v1a1 VM mutation webhook when v1a2 FSS is enabled
  webhooks/virtualmachine/webhooks.go
Labels: size/XS, cla-not-required

#261 🌱 Adds a Ready condition to CVMI and VMI resources
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha2/virtualmachineimage_types.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  pkg/conditions2/getter.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  test/builder/vcsim_test_context.go
Labels: size/L, testing-needed-e2e-fast, cla-not-required

#280 🐛 Fixes the reason to assert for CVMI workflow
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
Labels: size/XS, cla-not-required
