Repository vmware-tanzu/vm-operator, pull requests merged in 2023-06, with the labels that each got.

#152 Power State Enhancements
  .markdownlintrc
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  go.mod
  go.sum
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/vsphere/vm/internal/power_state_context_keys.go
  pkg/util/vsphere/vm/power_state.go
  pkg/util/vsphere/vm/power_state_test.go
  pkg/util/vsphere/vm/suite_test.go
  pkg/vmprovider/providers/vsphere/resources/vm.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/virtualmachine/delete.go
  pkg/vmprovider/providers/vsphere/virtualmachine/powerstate.go
  pkg/vmprovider/providers/vsphere/virtualmachine/powerstate_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  test/builder/util.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#154 Do not reconfig suspended VM pre power-on
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
Labels: cla-not-required

#159 🌱 Introduces new constant for PCI passthru vmx version
  pkg/vmprovider/providers/vsphere/constants/constants.go
Labels: size/XS, cla-not-required

#155 ✨ Support Restart
  .markdownlintrc
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  go.mod
  go.sum
  pkg/util/vsphere/vm/power_state.go
  pkg/util/vsphere/vm/power_state_test.go
  pkg/util/vsphere/vm/suite_test.go
  pkg/util/vsphere/vm/vm.go
  pkg/util/vsphere/vm/vm_test.go
  pkg/vmprovider/providers/vsphere/resources/vm.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/virtualmachine/delete.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#160 🐛 Set Hardware versions for VMs created with PVC/PCI devices
  pkg/util/devices.go
  pkg/util/devices_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_create.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#163 ✨ Support ControllerName for VM Class
  api/v1alpha1/virtualmachineclass_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachineclass_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  docs/concepts/workloads/vm-class.md
  pkg/lib/env.go
  pkg/util/kube/kube_suite_test.go
  pkg/util/kube/predicates.go
  pkg/util/kube/predicates_test.go
  webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator.go
  webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator_unit_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#166 ✨ Use Symlink or Docker for generate-go-conversions fallback
  Makefile
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full, cla-not-required

#169 🌱 Only sanitize virtual disks that are non-RDM from class config spec
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/devices.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required
