Repository vmware-tanzu/vm-operator, pull requests merged in 2023-03, with the labels that each got.

#68 Update servers TLS config to use approved cipher suites
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/default/manager_auth_proxy_patch.yaml
  go.mod
  go.sum
  main.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#70 Bump golangci-lint and remove unused tools
  .golangci.yml
  Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/vmprovider/providers/vsphere/config/config.go
  pkg/vmprovider/providers/vsphere/vcenter/getvm.go
  test/builder/flags.go
  test/builder/intg_test_context.go
  test/builder/test_suite.go
  test/builder/unit_test_context.go
  test/testutil/util.go
Labels: size/XL, testing-needed-e2e-fast

#71 Remove image supported VM validation check
  pkg/vmprovider/providers/vsphere/constants/constants.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast

#72 Bump up controller-runtime version
  controllers/virtualmachineservice/providers/simplelb/simplelb_provider.go
  controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go
  go.mod
  go.sum
  pkg/patch/patch_test.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_create.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachineservice/validation/virtualmachineservice_validator.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#76 Remove unused var from VM validation webhook
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XS

#78 Account for GPU devices when the DaynDate FSS is disabled
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#69 Add finalizer to VirtualMachinePublishRequest
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  pkg/context/virtualmachinepublishrequest_context.go
  test/builder/util.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full

#77 Add WCP_Namespaced_Class_And_Windows_Support FSS into VMOP
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  hack/deploy-wcp.sh
  pkg/lib/env.go
Labels: size/S

#85 Bootstrap Provider Docs
  docs/index.md
  docs/user-guide/bootstrap.md
  docs/user-guide/examples/demo.md
  mkdocs.yml
Labels: documentation, size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#87 docs: Build RTFD preview for PRs
  .github/workflows/pr-rtfd.yml
Labels: documentation, size/S

#86 sec: Disable Named Net Provider in Prod
  pkg/lib/env.go
  pkg/vmprovider/providers/vsphere/network/network_provider.go
  pkg/vmprovider/providers/vsphere/network/network_provider_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: bug, size/L, testing-needed-e2e-fast, testing-done-e2e-fast, security

#79 Remove VM image hardware version check in VM validation webhook.
  controllers/volume/volume_controller.go
  controllers/volume/volume_controller_suite_test.go
  controllers/volume/volume_controller_unit_test.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, testing-done-e2e-full

#91 Doc overhaul
  docs/favicon.ico
  docs/favicon.svg
  docs/index.md
  docs/requirements.txt
  docs/user-guide/bootstrap.md
  docs/user-guide/deployvm.md
  docs/www/css/vm-operator.css
  docs/www/img/favicon.png
  docs/www/themes/material/.icons/vm-op/logo-black-solid.svg
  docs/www/themes/material/.icons/vm-op/logo-black.svg
  docs/www/themes/material/.icons/vm-op/logo-white-solid.svg
  docs/www/themes/material/.icons/vm-op/logo-white.svg
  docs/www/themes/yeti/404.html
  docs/www/themes/yeti/base.html
  docs/www/themes/yeti/content.html
  docs/www/themes/yeti/css/base.css
  docs/www/themes/yeti/css/base.min.css
  docs/www/themes/yeti/css/bootstrap-custom.min.css
  docs/www/themes/yeti/css/font-awesome-4.7.0.css
  docs/www/themes/yeti/css/font-awesome-4.7.0.min.css
  docs/www/themes/yeti/css/highlight.css
  docs/www/themes/yeti/fonts/FontAwesome.otf
  docs/www/themes/yeti/fonts/fontawesome-webfont.eot
  docs/www/themes/yeti/fonts/fontawesome-webfont.svg
  docs/www/themes/yeti/fonts/fontawesome-webfont.ttf
  docs/www/themes/yeti/fonts/fontawesome-webfont.woff
  docs/www/themes/yeti/fonts/fontawesome-webfont.woff2
  docs/www/themes/yeti/js/base.js
  docs/www/themes/yeti/js/bootstrap-3.0.3.min.js
  docs/www/themes/yeti/js/highlight.pack.js
  docs/www/themes/yeti/js/jquery-1.10.2.min.js
  docs/www/themes/yeti/main.html
  docs/www/themes/yeti/nav-sub.html
  docs/www/themes/yeti/nav.html
  docs/www/themes/yeti/search-modal.html
  docs/www/themes/yeti/toc.html
  mkdocs.yml
Labels: documentation, size/XXL, testing-needed-e2e-fast

#80 PSP to PSA migration to support Kubernetes 1.25
  config/wcp/vmoperator/namespace_patch.yaml
Labels: size/XS

#74 Remove Scheme from ControllerManagerContext and Reconciler
  controllers/providerconfigmap/provider_configmap_controller.go
  controllers/providerconfigmap/provider_configmap_controller_unit_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go
  controllers/volume/volume_controller.go
  controllers/volume/volume_controller_unit_test.go
  pkg/context/controller_manager_context.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/manager/manager.go
  test/builder/unit_test_context.go
Labels: size/M

#83 Support for Sysprep / Windows images
  api/v1alpha1/virtualmachine_types.go
  docs/user-guide/deployvm.md
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: enhancement, size/L, testing-needed-e2e-fast, testing-done-e2e-fast, api

#90 Fix VirtualMachinePublishRequest controller test race
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
Labels: size/S

#93 Additional doc updates
  .gitignore
  .markdownlintrc
  Makefile
  docs/README.md
  docs/about/contributing.md
  docs/about/release-notes.md
  docs/apis/overview.md
  docs/concepts/README.md
  docs/concepts/api.md
  docs/concepts/components.md
  docs/concepts/images/README.md
  docs/concepts/images/pub-vm-image.md
  docs/concepts/images/vm-image.md
  docs/concepts/services-networking/README.md
  docs/concepts/services-networking/guest-net-config.md
  docs/concepts/services-networking/vm-service.md
  docs/concepts/workloads/README.md
  docs/concepts/workloads/guest.md
  docs/concepts/workloads/vm-class.md
  docs/concepts/workloads/vm-example.yaml
  docs/concepts/workloads/vm-web-console.md
  docs/concepts/workloads/vm.md
  docs/index.md
  docs/ref/README.md
  docs/ref/api/README.md
  docs/ref/api/v1alpha1.md
  docs/ref/config/README.md
  docs/ref/config/manager.md
  docs/ref/proj/README.md
  docs/ref/proj/build.md
  docs/ref/proj/docs.md
  docs/ref/proj/release.md
  docs/requirements.txt
  docs/start/README.md
  docs/start/about/README.md
  docs/start/about/license.md
  docs/start/about/release-notes.md
  docs/start/about/roadmap.md
  docs/start/contrib/README.md
  docs/start/contrib/report-issue.md
  docs/start/contrib/submit-change.md
  docs/start/contrib/suggest-change.md
  docs/start/help.md
  docs/start/quick.md
  docs/tutorials/README.md
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/deploy-vm/cloudinit.md
  docs/tutorials/deploy-vm/vappconfig.md
  docs/tutorials/troubleshooting/README.md
  docs/tutorials/troubleshooting/get-console-session.md
  docs/www/css/vm-operator.css
  mkdocs.yml
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast

#82 v1alpha2 APIs
  Makefile
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  api/v1alpha2/common/types.go
  api/v1alpha2/common/zz_generated.deepcopy.go
  api/v1alpha2/doc.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/sysprep/sysprep.go
  api/v1alpha2/sysprep/zz_generated.deepcopy.go
  api/v1alpha2/testdata/vm-with-cloudinit.yaml
  api/v1alpha2/testdata/vm-with-sysprep.yaml
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/virtualmachine_readiness_types.go
  api/v1alpha2/virtualmachine_storage_types.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachineclass_types.go
  api/v1alpha2/virtualmachineimage_types.go
  api/v1alpha2/virtualmachinepublishrequest_types.go
  api/v1alpha2/virtualmachineservice_types.go
  api/v1alpha2/virtualmachinesetresourcepolicy_types.go
  api/v1alpha2/virtualmachinetempl_types.go
  api/v1alpha2/virtualmachinewebconsolerequest_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
  docs/ref/api/README.md
  docs/ref/api/v1alpha2.md
  mkdocs.yml
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast, work-in-progress, api

#88 Add new deploy-wcp script
  .dockerignore
  .gitignore
  Makefile
  hack/deploy-wcp.sh
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#130 Update testing-needed workflow to prevent label race
  .github/configs/labeler.yml
  .github/workflows/testing-needed.yml
Labels: size/M

#127 Fix VirtualMachinePublishRequest integration test race.
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
Labels: size/S

#92 Add finalizer for vmi and cvmi resources
  api/v1alpha1/condition_consts.go
  config/rbac/role.yaml
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/utils/constants.go
  controllers/contentlibrary/utils/test_utils.go
  controllers/contentlibrary/utils/utils.go
  pkg/context/clustercontentlibraryitem_context.go
  pkg/context/contentlibraryitem_context.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast

#129 Remove VirtualMachineClassBinding logic
  controllers/virtualmachine/virtualmachine_controller.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast

#128 Add initial v1alpha2 conversion
  Makefile
  api/go.mod
  api/go.sum
  api/utilconversion/conversion_fuzz.go
  api/v1alpha1/condition_conversion.go
  api/v1alpha1/contentlibraryprovider_types.go
  api/v1alpha1/contentsource_types.go
  api/v1alpha1/contentsourcebinding_types.go
  api/v1alpha1/conversion_test.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/virtualmachineclass_conversion.go
  api/v1alpha1/virtualmachineclass_types.go
  api/v1alpha1/virtualmachineclassbinding_types.go
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha1/virtualmachinepublishrequest_conversion.go
  api/v1alpha1/virtualmachinepublishrequest_types.go
  api/v1alpha1/virtualmachineservice_conversion.go
  api/v1alpha1/virtualmachineservice_types.go
  api/v1alpha1/virtualmachinesetresourcepolicy_conversion.go
  api/v1alpha1/virtualmachinesetresourcepolicy_types.go
  api/v1alpha1/webconsolerequest_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  api/v1alpha2/common/zz_generated.deepcopy.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/sysprep/zz_generated.deepcopy.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachineclass_conversion.go
  api/v1alpha2/virtualmachineclass_types.go
  api/v1alpha2/virtualmachineimage_conversion.go
  api/v1alpha2/virtualmachineimage_types.go
  api/v1alpha2/virtualmachinepublishrequest_conversion.go
  api/v1alpha2/virtualmachinepublishrequest_types.go
  api/v1alpha2/virtualmachineservice_conversion.go
  api/v1alpha2/virtualmachineservice_types.go
  api/v1alpha2/virtualmachinesetresourcepolicy_conversion.go
  api/v1alpha2/virtualmachinesetresourcepolicy_types.go
  api/v1alpha2/virtualmachinewebconsolerequest_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  go.mod
  go.sum
  hack/boilerplate/boilerplate.generatego.txt
  hack/tools/Makefile
Labels: size/XXL, testing-needed-e2e-fast, testing-done-e2e-fast
