Repository vmware-tanzu/vm-operator, pull requests merged in 2023-12, with the labels that each got.

#282 🌱 Adds api unit tests to Makefile
  api/v1alpha1/virtualmachineimage_conversion.go
  hack/test-unit.sh
Labels: size/S, cla-not-required

#279 :warning: Change v1a2 VM spec fields of type struct to ptrs
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_provider.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_intg_test.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_unit_test.go
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_unit_test.go
  pkg/prober2/probe/heartbeat_test.go
  pkg/prober2/probe/tcp.go
  pkg/prober2/probe/tcp_test.go
  pkg/prober2/prober_manager.go
  pkg/prober2/prober_manager_test.go
  pkg/prober2/worker/readiness_worker.go
  pkg/prober2/worker/readiness_worker_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/vcenter/getvm.go
  pkg/vmprovider/providers/vsphere2/vcenter/getvm_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/storage.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  test/builder/utila2.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, testing-needed-e2e-fast, cla-not-required

#283 ✨ Notify Google Chat workflows
  .github/workflows/notify-gchat-on-issue-comment.yml
  .github/workflows/notify-gchat-on-issue.yml
  .github/workflows/notify-gchat-on-pr.yml
Labels: size/L, testing-needed-e2e-fast, cla-not-required

#281 ✨Move tkg vmware-system-* annotations to vmi/cvmi status
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachineimage_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#284 Fix network name validation to use DNSSubDomain
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/S, cla-not-required

#288 🐛 Check probe spec pointers for nil during conversion
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
Labels: size/S, cla-not-required

#290 🌱 Fix getting the user login in MR opened action
  .github/workflows/gnotify.py
Labels: size/XS, cla-not-required

#286 ✨ Honor SecretKeySelector Optional in v1a2 bootstrap
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#294 🐛 Check VM.Spec.Network for nil in v1a2 mutation wehbook
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
Labels: size/S, cla-not-required

#292 ⚠️ Remove VM ReadinessGates from v1a2
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_readiness_types.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/M, cla-not-required

#297 🌱 Remove old v1a2 helper function in the VM validation webhook
  controllers/volume/v1alpha2/volume_controller.go
  webhooks/virtualmachine/v1alpha2/validation/helpers.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
Labels: size/M, cla-not-required

#301 🌱 Remove Optional from SecretKeySelector
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  api/v1alpha2/common/types.go
  api/v1alpha2/common/zz_generated.deepcopy.go
  api/v1alpha2/sysprep/sysprep.go
  api/v1alpha2/sysprep/zz_generated.deepcopy.go
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_provider.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_vappconfig_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, cla-not-required

#302 🐛 Fixes VMI/CVMI condition conversion
  api/v1alpha1/virtualmachineimage_conversion.go
Labels: size/M, testing-needed-e2e-fast, cla-not-required

#296 🌱 Remove v1a2 VirtualMachineClass annotation conversion
  api/v1alpha1/virtualmachineclass_conversion.go
Labels: size/S, cla-not-required

#303 ✨ Support for inline cloud-init
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  go.mod
  pkg/vmprovider/providers/vsphere2/cloudinit/cloudconfig.go
  pkg/vmprovider/providers/vsphere2/cloudinit/cloudconfig_secret.go
  pkg/vmprovider/providers/vsphere2/cloudinit/cloudconfig_secret_test.go
  pkg/vmprovider/providers/vsphere2/cloudinit/cloudconfig_test.go
  pkg/vmprovider/providers/vsphere2/cloudinit/cloudinit_suite_test.go
  pkg/vmprovider/providers/vsphere2/cloudinit/validate/validate.go
  pkg/vmprovider/providers/vsphere2/cloudinit/validate/validate_suite_test.go
  pkg/vmprovider/providers/vsphere2/cloudinit/validate/validate_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
Labels: size/XXL, testing-needed-e2e-fast, cla-not-required

#307 🐛 Fix bugs in vApp bootstrap docs
  docs/concepts/workloads/guest.md
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/deploy-vm/cloudinit.md
  docs/tutorials/deploy-vm/vappconfig.md
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#285 ✨ Set more useful interface name in v1a2 VM Status
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: size/M, testing-done-e2e-fast, cla-not-required

#295 ⚠️ Add note that the TCPSocket probe method is deprecated
  .golangci.yml
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_readiness_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/S, cla-not-required

#305 ✨ Validate CloudConfig using schema
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/tools.go
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_secret.go
  pkg/util/cloudinit/cloudconfig_secret_test.go
  pkg/util/cloudinit/cloudconfig_test.go
  pkg/util/cloudinit/cloudinit_suite_test.go
  pkg/util/cloudinit/schema/.gitignore
  pkg/util/cloudinit/schema/Dockerfile.quicktype
  pkg/util/cloudinit/schema/Makefile
  pkg/util/cloudinit/schema/README.md
  pkg/util/cloudinit/schema/cloudconfig.go
  pkg/util/cloudinit/schema/package-lock.json
  pkg/util/cloudinit/schema/package.json
  pkg/util/cloudinit/schema/schema-cloud-config-v1.json
  pkg/util/cloudinit/validate/testdata/README.md
  pkg/util/cloudinit/validate/testdata/invalid-cloud-config-1.yaml
  pkg/util/cloudinit/validate/testdata/valid-cloud-config-1.yaml
  pkg/util/cloudinit/validate/validate.go
  pkg/util/cloudinit/validate/validate_suite_test.go
  pkg/util/cloudinit/validate/validate_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
Labels: size/XXL, testing-needed-e2e-fast, cla-not-required

#310 🐛 Restore previous LinuxPrep default customization behavior
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
Labels: size/XS, cla-not-required

#308 🐛 Check for well-known CloudInit userdata keys
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/M, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#309 🐛 Fix NPE when VM does not have a Reserved field
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller.go
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_unit_test.go
Labels: size/S, cla-not-required

#300 ⚠️ Mark the v1a1 VirtualMachineImage ContentLibraryRef field as deprecated
  .golangci.yml
  api/v1alpha1/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
Labels: size/S, cla-not-required

#312 🐛 Fix generated CloudConfig type via Docker
  pkg/util/cloudinit/schema/Makefile
Labels: bug, size/XS, cla-not-required

#304 ✨ Add VirtualMachine conversion tests
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  pkg/vmprovider/providers/vsphere2/network/network_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#306 🐛 Set Namespace in v1a1 VirtualMachineImage ProviderRef
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/virtualmachineimage_conversion_test.go
  controllers/contentlibrary/v1alpha1/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha1/utils/test_utils.go
Labels: size/M, testing-needed-e2e-fast, cla-not-required

#315 🐛 Add provider test for nil v1a2 VM Spec nil fields
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
Labels: size/M, cla-not-required

#313 🌱 Add conversion annotation to CVMI/VMI to populate missing field
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/virtualmachineimage_conversion_test.go
  api/v1alpha2/virtualmachineimage_types.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
Labels: size/L, cla-not-required

#316 🌱 Moves common annotation logic to util package
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/utils/utils.go
  controllers/contentlibrary/v1alpha2/utils/utils_test.go
Labels: size/L, cla-not-required

#318 🐛 Fix cloudconfig runcmd / YAML->JSON on parse
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_secret.go
  pkg/util/cloudinit/cloudconfig_secret_test.go
  pkg/util/cloudinit/cloudconfig_test.go
  pkg/util/cloudinit/validate/validate.go
  pkg/util/cloudinit/validate/validate_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/L, cla-not-required

#317 🌱 Rename inlined CloudInit default user field
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/testdata/vm-with-cloudinit.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/S, cla-not-required

#319 📖 Tutorial on deploying NFS server/client
  docs/tutorials/deploy-apps/README.md
  docs/tutorials/deploy-apps/nfs-server-and-client.md
  mkdocs.yml
Labels: documentation, size/L

#321 🌱 Update GitHub actions versions
  .github/workflows/ci.yml
  .github/workflows/gnotify.yml
  .github/workflows/post-coverage-to-pr.yml
  .github/workflows/testing-needed.yml
Labels: size/M, cla-not-required

#322 🌱 Update mkdocs ver & deps ver & build-docs mk
  .gitignore
  Makefile
  docs/requirements.txt
  docs/start/contrib/submit-change.md
  mkdocs.yml
Labels: size/M, cla-not-required

#320 ✨ GitHub action to verify docs
  .github/workflows/ci.yml
  Makefile
Labels: size/M, cla-not-required

#325 🐛 Do not always initialize v1a2 VM Spec.Advanced field
  pkg/vmprovider/providers/vsphere2/session/session_vm.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create_clone.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/S, cla-not-required

#276 🌱 Update deprecated pr labeler version
  .github/configs/labeler.yml
  .github/workflows/pr-labeler.yml
Labels: size/S

#324 🌱 Update v1a2 VM printer columns
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/S, cla-not-required

#323 🐛 Update VM Class scope in test builder for FSS
  test/builder/test_suite.go
Labels: bug, size/S, cla-not-required

#311 🌱 Refactor v1a2 backup to store all VM additional resources YAML in ExtraConfig
  api/v1alpha2/virtualmachine_types.go
  pkg/context/backupvirtualmachine_context.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required
