Repository vmware-tanzu/vm-operator, pull requests merged in 2023-10, with the labels that each got.

#237 🌱 Prevent non-admin users from setting first-boot-done annotation
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-full, cla-not-required

#236 🐛 Fix a few typos in the v1a2 bootstrap types
  api/v1alpha2/common/types.go
  api/v1alpha2/sysprep/sysprep.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/S, cla-not-required

#235 :bug: Return err during unmarshaling ovf file to trigger reconcile
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_test.go
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_provider.go
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_test.go
Labels: size/S, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#231 :seedling: Emit a webhook warning when OvfEnv or ExtraConfig transport is specified
  webhooks/common/response.go
  webhooks/common/response_test.go
  webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#238 🌱 Reverse configSpec.firmware order of precedence to Image then Classes
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
Labels: size/M, cla-not-required

#244 :seedling: Add vulncheck local make target and GH action
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#242 ✨ Add v1a2 webconsolerequest validation webhooks
  config/webhook/manifests.yaml
  test/builder/utila2.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_intg_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_suite_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_unit_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/webhooks.go
  webhooks/virtualmachinewebconsolerequest/webhooks.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#246 ✨ Set v1a2 as the storageVersion
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/virtualmachineclass_types.go
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha1/virtualmachinepublishrequest_types.go
  api/v1alpha1/virtualmachineservice_types.go
  api/v1alpha1/virtualmachinesetresourcepolicy_types.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachineclass_types.go
  api/v1alpha2/virtualmachineimage_types.go
  api/v1alpha2/virtualmachinepublishrequest_types.go
  api/v1alpha2/virtualmachineservice_types.go
  api/v1alpha2/virtualmachinesetresourcepolicy_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
Labels: size/M, cla-not-required

#245 :seedling: Platform-aware tooling
  Makefile
  hack/ensure-kustomize.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#247 🌱Include the v1a2 webconsole CRD in the combined CRD manifest
  config/crd/kustomization.yaml
Labels: size/XS, cla-not-required

#241 ✨ Improve v1a2 VM Network validation checks
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#243 🌱 Add friendly image name support in v1a2 and improve duplicate check
  docs/concepts/images/vm-image.md
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#215 🌱 Rename IMAGE-NAME to HUMAN-READABLE-NAME in VM Image printer column
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha2/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
Labels: size/S, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#248 🌱 Adopt image display name in API and docs
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha1/virtualmachinepublishrequest_types.go
  api/v1alpha2/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  docs/concepts/images/vm-image.md
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#250 🌱 Fix deploy-local script for v1a2 disabled scenarios
  hack/deploy-local.sh
Labels: size/S, cla-not-required

#239 ✨ Update VM backup to skip unchanged data and include instance ID
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha1/virtualmachine_controller_unit_test.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/vmprovider/fake/fake_vm_provider.go
  pkg/vmprovider/interface.go
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_util.go
  pkg/vmprovider/providers/vsphere/session/session_util_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
  pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/session/session_util.go
  pkg/vmprovider/providers/vsphere2/session/session_util_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#240 🌱 Add VM backup implementation for v1a2
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller_unit_test.go
  pkg/vmprovider/fake/fake_vm_provider_a2.go
  pkg/vmprovider/interface_a2.go
  pkg/vmprovider/providers/vsphere2/constants/constants.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/virtualmachine_suite_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#252 🌱 Update controller-tools to v0.12.0
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/crd/bases/vmoperator.vmware.com_contentsourcebindings.yaml
  config/crd/bases/vmoperator.vmware.com_contentsources.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
  config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraryitems.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitemimportrequests.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitems.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#249 ✨ Synthesize v1a1 Prereq condition from v1a2 conditions
  api/v1alpha1/virtualmachine_conversion.go
Labels: size/M, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#256 🌱 Enabled v1a1 VM mutation webhooks on v1a2 FSS enabled env
  webhooks/virtualmachine/webhooks.go
Labels: size/XS, cla-not-required

#255 ✨ Mark v1a2 VirtualMachineClass as namespace scoped
  api/v1alpha2/virtualmachineclass_types.go
Labels: size/XS, cla-not-required

#251 🐛 Various v1a2 bug fixes
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/network/gosc_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_linuxprep_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
Labels: size/M, cla-not-required

#254 ✨ Reduce some clutter in v1a2 Status.Network
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#253 ✨ Finalize network v1a2 naming convention
  pkg/vmprovider/providers/vsphere2/network/network.go
  pkg/vmprovider/providers/vsphere2/network/network_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#258 :seedling: Allow privileged users to modify annotations on a VirtualMachine object
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/builder/auth.go
  pkg/builder/mutating_webhook.go
  pkg/builder/validating_webhook.go
  pkg/lib/env.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required

#260 🐛 Addressing dependabot alerts
  api/go.mod
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, cla-not-required

#257 ✨ Persist PVC related info in VM ExtraConfig for backup
  pkg/context/backupvirtualmachine_context.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/XL, testing-needed-e2e-fast, testing-done-e2e-fast, cla-not-required
