Repository vmware-tanzu/vm-operator, pull requests merged in 2024-02, with the labels that each got.

#375 🌱 Simplify get storage policy ID from storage class name
  pkg/vmprovider/providers/vsphere/storage/storageclass.go
Labels: size/M, cla-not-required

#378 :sparkles: Introduce Network Provider Type NSXT_VPC
  external/ncp/api/v1alpha1/virtualnetwork_types.go
  pkg/config/config.go
Labels: size/XS, cla-not-required

#367 🌱 Remove v1a2 volume controller helpers
  controllers/volume/v1alpha2/helpers.go
  controllers/volume/v1alpha2/volume_controller.go
  controllers/volume/v1alpha2/volume_controller_intg_test.go
  controllers/volume/v1alpha2/volume_controller_unit_test.go
Labels: size/M, cla-not-required

#380 🐛 Add GVK in additional resource backup
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/M, cla-not-required

#382 🐛 Set Sysprep bootstrap secret data in createArgs & updateArgs
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/XS, cla-not-required

#377 🐛 Remove backingless VirtualEthernetCards from placement ConfigSpec
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
Labels: size/M, cla-not-required

#368 🌱 Commonize setting of optional VM ready conditions
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
Labels: size/M, cla-not-required

#383 🌱 Preserve class ConfigSpec Annotation if set
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
Labels: size/S, cla-not-required

#374 🐛 Disallow empty sysPrep bootstrap
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#384 🌱 Make manager the default container
  Makefile
  config/default/kustomization.yaml
  config/default/manager_default_container_patch.yaml
  hack/deploy-local-certmanager.sh
Labels: size/S, cla-not-required

#385 :sparkles: Add VPC network types to v1alpha1 API and support version conversion
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha1.md
  pkg/vmprovider/providers/vsphere2/network/network.go
Labels: size/M, cla-not-required

#379 🌱 Simplify check if a device is a VirtualEthernetCard
  pkg/util/devices.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
Labels: size/S, cla-not-required

#365 🌱 Include required storage class in StorageReady condition
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/storage/storageclass.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
Labels: size/L, cla-not-required

#387 :sparkles: Import VPC API from nsx-operator
  go.mod
  go.sum
  pkg/manager/manager.go
  test/builder/fake.go
Labels: size/S, cla-not-required

#388 🌱 Add validation for autoLogonCount and update description
  api/v1alpha2/sysprep/sysprep.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#392 :sparkles: Add default NetworkInterface when VPC network
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
Labels: size/S, cla-not-required

#394 🐛 Add back the V1Alpha1Compatible image condition to v1a2
  api/v1alpha2/virtualmachineimage_types.go
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
Labels: size/L, cla-not-required

#393 📖 Note that HostName is used as Windows Computer Name
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/XS, cla-not-required

#372 🌱 Ensure Network field is set in network interfaces
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
Labels: size/M, cla-not-required

#395 🐛 Check for GuestInfo prober exclusivity in validation webhook
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/S, cla-not-required

#391 🌱 Make more v1a2 VM Status Network fields pointers
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: size/L, cla-not-required

#397 :sparkles: Update vcsim test frame for VPC networking
  test/builder/vcsim_test_context.go
Labels: size/XS, cla-not-required

#400 🐛 Always set v1a1 CloudInit transport when v1a2 is using CloudInit
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
Labels: size/S, cla-not-required

#399 ✨Add SSH password authentication to inline cloud-init
  api/v1alpha2/cloudinit/cloudconfig.go
  api/v1alpha2/cloudinit/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
Labels: size/M, cla-not-required

#405 🌱 Use API VirtualMachineImageV1Alpha1Compatible const
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/XS, cla-not-required

#404 🌱 Assign whole BootstrapData struct in VM update reconcile path
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/XS, cla-not-required

#398 🐛 Only update CloudInit ConfigSpec if updates are required
  pkg/util/configspec.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/L, cla-not-required

#403 :sparkles: Create SubnetPort when realizing VPC networking
  config/rbac/role.yaml
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  pkg/vmprovider/providers/vsphere2/constants/constants.go
  pkg/vmprovider/providers/vsphere2/network/network.go
  pkg/vmprovider/providers/vsphere2/network/network_test.go
  pkg/vmprovider/providers/vsphere2/network/nsxt.go
  pkg/vmprovider/providers/vsphere2/network/nsxt_test.go
  test/builder/fake.go
Labels: size/L, cla-not-required

#407 🌱 Remove v1a1 imports from v1a2 code
  pkg/vmprovider/providers/vsphere2/placement/cluster_placement_test.go
  pkg/vmprovider/providers/vsphere2/placement/zone_placement_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_test.go
  webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator.go
  webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator_unit_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_unit_test.go
Labels: size/M, cla-not-required

#408 ✨ Use ginkgo in hack/test files
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/test-integration.sh
  hack/test-unit.sh
  hack/test.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/builder/flags.go
Labels: size/L, cla-not-required
