Repository vmware-tanzu/vm-operator, pull requests merged in 2024-05, with the labels that each got.

#494 🐛 Disable spec.biosUUID privilege check
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/S, cla-not-required

#484 🌱 Make LinuxPrep.HWClockIsUTC nillable
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_bootstrap_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep_test.go
Labels: size/M, cla-not-required

#496 🌱 Update GitHub actions to exclude generated files when checking diff
  .github/configs/labeler.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/testing-needed.yml
Labels: size/M, cla-not-required

#497 📖 Invert kubebuilder annotations
  api/v1alpha3/cloudinit/cloudconfig.go
  api/v1alpha3/common/types.go
  api/v1alpha3/doc.go
  api/v1alpha3/sysprep/sysprep.go
  api/v1alpha3/virtualmachine_bootstrap_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_readiness_types.go
  api/v1alpha3/virtualmachine_storage_types.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/virtualmachineclass_types.go
  api/v1alpha3/virtualmachineimage_types.go
  api/v1alpha3/virtualmachinepublishrequest_types.go
  api/v1alpha3/virtualmachineservice_types.go
  api/v1alpha3/virtualmachinesetresourcepolicy_types.go
  api/v1alpha3/virtualmachinetempl_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XXL, cla-not-required

#495 🌱 Store resolved Cloud-Init instance ID in spec
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha3.md
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
Labels: size/M, cla-not-required

#493 :seedling: Update VPC networking NSX SubnetPort APIs
  go.mod
  go.sum
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
Labels: size/M, cla-not-required

#500 🌱 Make VM Spec ChangeBlockTracking nillable
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
Labels: size/M, cla-not-required

#498 🐛 Honor v1a1 VMMetadata ConfigMapName in v1a3 using annotations
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/L, cla-not-required

#499 ✨ Introduce the VirtualMachineReplicaSet API
  api/v1alpha3/common/types.go
  api/v1alpha3/common/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachinereplicaset_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_virtualmachinereplicasets.yaml
  config/crd/patches/webhook_in_virtualmachinereplicasets.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/controllers.go
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  pkg/context/virtualmachinereplicaset_context.go
  test/builder/utila2.go
  webhooks/virtualmachinereplicaset/mutation/virtualmachinereplicaset_mutator.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator_intg_test.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator_suite_test.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator_unit_test.go
  webhooks/virtualmachinereplicaset/webhooks.go
  webhooks/webhooks.go
Labels: size/XXL, cla-not-required

#502 ✨ Add FSS_WCP_VMSERVICE_RESIZE
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#506 🌱 Go 1.22.3
  .github/workflows/ci.yml
  Dockerfile
Labels: size/XS, cla-not-required

#508 🌱 Remove "A2" suffix from dummy object function names
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  controllers/volume/volume_controller_intg_test.go
  pkg/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/providers/vsphere/placement/cluster_placement_test.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/virtualmachine/delete_test.go
  pkg/providers/vsphere/virtualmachine/publish_test.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/util/vmopv1/vm_test.go
  test/builder/dummies.go
  test/builder/util.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator_intg_test.go
  webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator_unit_test.go
  webhooks/virtualmachineclass/validation/virtualmachineclass_validator_intg_test.go
  webhooks/virtualmachineclass/validation/virtualmachineclass_validator_unit_test.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_unit_test.go
  webhooks/virtualmachineservice/mutation/virtualmachineservice_mutator_intg_test.go
  webhooks/virtualmachineservice/mutation/virtualmachineservice_mutator_unit_test.go
  webhooks/virtualmachineservice/validation/virtualmachineservice_validator_intg_test.go
  webhooks/virtualmachineservice/validation/virtualmachineservice_validator_unit_test.go
  webhooks/virtualmachinesetresourcepolicy/validation/virtualmachinesetresourcepolicy_validator_intg_test.go
  webhooks/virtualmachinesetresourcepolicy/validation/virtualmachinesetresourcepolicy_validator_unit_test.go
Labels: size/XL, cla-not-required

#503 🌱 Allow updates to ClassName when VM resize is enabled
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#501 :bug: Upgrade VMs for use with Instance ID Discovery
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_intg_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#511 🌱 Add very basic resize config spec function
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
  pkg/util/resize/resize_suite_test.go
Labels: size/L, cla-not-required

#509 🌱 Remove duplicated log in VM controller
  controllers/virtualmachine/virtualmachine_controller.go
Labels: size/XS, cla-not-required

#507 🌱 Add last VM Resize annotation
  pkg/util/vmopv1/resize.go
  pkg/util/vmopv1/resize_test.go
Labels: size/L, cla-not-required

#489 :book: Update doc regarding pause annotation and ec key
  docs/concepts/workloads/vm-controller.md
Labels: size/S, cla-not-required

#516 ✨ Add FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/XS, cla-not-required

#513 🐛 Fix requeue delay if trying to create VMs (8.0U3 x-port)
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
Labels: size/XS, cla-not-required

#519 🌱 Support system:masters for IsPrivilegedUser
  pkg/builder/auth.go
  pkg/builder/auth_test.go
  pkg/builder/builder_suite_test.go
Labels: size/L, cla-not-required

#518 🌱 Protect VirtualMachine spec.biosUUID
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L, cla-not-required

#505 :sparkles: Support DHCP for VPC networking
  pkg/providers/vsphere/network/network.go
Labels: size/XS, cla-not-required

#521 🐛 Add FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET to yaml
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
Labels: size/XS, cla-not-required

#514 🌱 Add integration tests to cover VM create requeue delays
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine_controller_suite_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/L, cla-not-required

#523 🐛 Fix make generate
  Makefile
  api/v1alpha3/virtualmachine_types.go
Labels: size/XS, cla-not-required

#522 🐛 Fix verify-codegen.sh to get exit code correctly
  hack/verify-codegen.sh
Labels: size/XS, cla-not-required

#517 ✨ Add VirtualMachineSpec.InstanceUUID
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_intg_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#510 ✨ Support for classless VirtualMachine resources
  api/v1alpha2/virtualmachineclass_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/virtualmachineclass_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/volume/volume_controller.go
  pkg/constants/constants.go
  pkg/context/virtualmachine_context.go
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vcenter/getvm.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  pkg/util/vsphere/vm/vm.go
  pkg/util/vsphere/vm/vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XXL, cla-not-required

#520 ✨ Plumb through basic end to end resize
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
  test/builder/vcsim_test_context.go
Labels: size/L, cla-not-required

#492 docs: add spec.biosUUID and cloudInit.instanceID
  docs/concepts/workloads/guest.md
  docs/concepts/workloads/vm.md
Labels: size/S, cla-not-required

#524 ✨ Support for imageless VirtualMachine resources
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#527 🐛 Update govmomi to consume https://github.com/vmware/govmomi/pull/3446
  api/v1alpha3/zz_virtualmachine_guestosid_generated.go
  go.mod
  go.sum
  pkg/util/configspec_test.go
  pkg/util/vsphere/vm/hardware_version.go
  test/builder/vcsim_test_context.go
Labels: size/S, cla-not-required

#526 🐛 Check for valid image OS image labels keys and values
  pkg/util/image/status_to_label.go
  pkg/util/image/status_to_label_test.go
Labels: size/M, cla-not-required

#525 🌱 Compare basic ConfigSpec.Hardware fields for resize
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#529 🌱 Override resize ConfigSpec fields from VM Spec
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/resize/configspec_test.go
  pkg/util/vmopv1/resize_devops.go
  pkg/util/vmopv1/resize_devops_test.go
Labels: size/L, cla-not-required

#530 🌱 Remove ClusterModule & Content Library clients from vSphere client
  pkg/providers/vsphere/client/client.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_resourcepolicy.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/M, cla-not-required

#532 🌱 Generate topology API CRDs & rm from infra yaml
  Makefile
  config/crd/external-crds/topology.tanzu.vmware.com_availabilityzones.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_vspherezones.yaml
  config/default/kustomization.yaml
  go.mod
Labels: size/L, cla-not-required

#531 🌱 Add validations to minHardwareVersion to not exceed max supported hardware version
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#534 🌱 Controller-Runtime v0.18.2
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  controllers/infra/configmap/infra_configmap_controller.go
  controllers/infra/secret/infra_secret_controller.go
  controllers/volume/volume_controller.go
  go.mod
  go.sum
  pkg/builder/mutating_webhook.go
  pkg/builder/validating_webhook.go
  pkg/util/kube/predicates.go
  webhooks/virtualmachineservice/validation/virtualmachineservice_validator.go
Labels: size/L, cla-not-required

#533 🌱 Import net-operator API instead of vendoring it
  .gitignore
  Makefile
  config/crd/external-crds/netoperator.vmware.com_networkinterfaces.yaml
  config/crd/external-crds/netoperator.vmware.com_vmxnet3networkinterfaces.yaml
  config/local/vmoperator/kustomization.yaml
  config/rbac/role.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  external/net-operator/api/v1alpha1/groupversion_info.go
  external/net-operator/api/v1alpha1/networkinterface_types.go
  external/net-operator/api/v1alpha1/vmxnet3networkinterface_types.go
  external/net-operator/api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  test/builder/fake.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
Labels: size/L, cla-not-required

#535 🌱 Ginkgo v2.19.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, cla-not-required

#537 📖 Deploy VM w additional disk from PVC
  .markdownlintrc
  docs/tutorials/deploy-vm/with-pvc.md
  mkdocs.yml
Labels: size/L, cla-not-required

#538 🌱 Replace github.com/pkg/errors with stdlib errors
  controllers/controllers.go
  controllers/infra/controllers.go
  controllers/util/encoding/encoding.go
  controllers/util/remote/remote.go
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachineclass/virtualmachineclass_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/getter_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/patch.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/setter_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/utils.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/patch/patch.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_controller.go
  controllers/volume/volume_controller.go
  go.mod
  pkg/builder/mutating_webhook.go
  pkg/builder/validating_webhook.go
  pkg/conditions/getter_test.go
  pkg/conditions/patch.go
  pkg/conditions/setter_test.go
  pkg/conditions/utils.go
  pkg/manager/manager.go
  pkg/patch/patch.go
  pkg/prober/worker/readiness_worker.go
  pkg/providers/vsphere/config/config.go
  pkg/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/providers/vsphere/credentials/credentials.go
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/storage/provisioning.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/vmlifecycle/create_clone.go
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/vmopv1/vm.go
  pkg/util/vsphere/client/client.go
  test/builder/test_suite.go
  webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator.go
  webhooks/persistentvolumeclaim/webhook.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator.go
  webhooks/virtualmachineclass/validation/virtualmachineclass_validator.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinereplicaset/mutation/virtualmachinereplicaset_mutator.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator.go
  webhooks/virtualmachineservice/mutation/virtualmachineservice_mutator.go
  webhooks/virtualmachineservice/validation/virtualmachineservice_validator.go
  webhooks/virtualmachinesetresourcepolicy/validation/virtualmachinesetresourcepolicy_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/webhooks.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/webhooks.go
  webhooks/webhooks.go
Labels: size/L, cla-not-required

#540 🌱 Exclude ./api from coverage (but still test it)
  Makefile
  hack/test.sh
Labels: size/M, cla-not-required

#541 🌱 Make pkg/util/ptr.Overwrite more generic
  pkg/util/ptr/ptr.go
  pkg/util/ptr/ptr_test.go
Labels: size/L, cla-not-required

#542 🌱 Replace gopkg.in/yaml.v3 with sigs.k8s.io/yaml
  controllers/infra/configmap/infra_configmap.go
  controllers/infra/configmap/infra_configmap_controller_intg_test.go
  go.mod
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
  pkg/util/cloudinit/validate/validate.go
Labels: size/L, cla-not-required

#544 🐛 Fix issue missed by bad GH action runs w yaml enc
  controllers/infra/configmap/infra_configmap_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/XS, cla-not-required

#545 :bug: Update finalizers to conform to upstream standards
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/utils/constants.go
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_unit_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller_intg_test.go
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller.go
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_unit_test.go
  test/builder/dummies.go
Labels: size/L, cla-not-required

#543 ✨ Go mod updates
  .golangci.yml
  Makefile
  api/go.mod
  api/go.sum
  api/v1alpha1/virtualmachine_conversion.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/crd/bases/vmoperator.vmware.com_contentsourcebindings.yaml
  config/crd/bases/vmoperator.vmware.com_contentsources.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
  config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraryitems.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitemimportrequests.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitems.yaml
  config/crd/external-crds/netoperator.vmware.com_networkinterfaces.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_availabilityzones.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_vspherezones.yaml
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  main.go
  pkg/docs/concepts/vm-class_test.go
  pkg/gen/guestosid/guestosid.go
  pkg/providers/vsphere/session/session_vm_update.go
Labels: size/L, cla-not-required

#546 🌱 Lint allowed/denied packages
  .golangci.yml
Labels: size/M, cla-not-required

#547 🌱 Update k8s.io/code-generator to 0.30.1
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S, cla-not-required

#548 🌱 Increase coverage for pkg/topology to above 90%
  pkg/topology/availability_zones_test.go
Labels: size/M, cla-not-required

#549 🌱 Fix issue with pkg/patch coverage
  pkg/patch/patch_test.go
  pkg/patch/suite_test.go
Labels: size/XS, cla-not-required

#554 🐛 Fix issue reading infra config map tags
  controllers/infra/configmap/infra_configmap.go
  controllers/infra/configmap/infra_configmap_test.go
Labels: size/S, cla-not-required

#528 :sparkles: VirtualMachineReplicaSet CRUD/Scale Up Scale Down support
  api/v1alpha3/virtualmachinereplicaset_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/rbac/role.yaml
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_intg_test.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_suite_test.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_delete_policy.go
  pkg/util/replicaset_label.go
  pkg/util/replicaset_label_test.go
Labels: size/XXL, cla-not-required
