Repository vmware-tanzu/vm-operator, pull requests merged in 2024-03, with the labels that each got.

#409 ✨ Add GuestDeviceName to network interfaces spec
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/network/netplan.go
  pkg/vmprovider/providers/vsphere2/network/netplan_test.go
  pkg/vmprovider/providers/vsphere2/network/network.go
  pkg/vmprovider/providers/vsphere2/network/network_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#410 🌱 Only default to LinuxPrep GOSC on Linux VMs
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
Labels: size/M, cla-not-required

#411 :sparkles: Add VM create/update e2e testing for VPC networking
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
Labels: size/L, cla-not-required

#390 ✨ Make the VM network interfaces immutable
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#413 🐛 Fix linter config after rm v1a1 bits
  .golangci.yml
  main.go
  pkg/webconsolevalidation/server.go
Labels: size/M, cla-not-required

#414 🌱 Remove cache work-around for ConfigMaps/Secrets and centralize infra controllers
  config/rbac/role.yaml
  controllers/controllers.go
  controllers/infra/configmap/infra_configmap.go
  controllers/infra/configmap/infra_configmap_controller.go
  controllers/infra/configmap/infra_configmap_controller_intg_test.go
  controllers/infra/configmap/infra_configmap_suite_test.go
  controllers/infra/configmap/infra_configmap_test.go
  controllers/infra/controllers.go
  controllers/infra/node/infra_node_controller.go
  controllers/infra/node/infra_node_controller_intg_test.go
  controllers/infra/node/infra_node_controller_suite_test.go
  controllers/infra/secret/infra_secret_controller.go
  controllers/infra/secret/infra_secret_controller_intg_test.go
  controllers/infra/secret/infra_secret_controller_suite_test.go
  controllers/infracluster/infracluster_controller.go
  controllers/infracluster/infracluster_controller_intg_test.go
  pkg/manager/cache.go
  pkg/manager/manager.go
Labels: size/XXL, cla-not-required

#421 🌱 Bump go version to 1.21.8
  .github/workflows/ci.yml
  Dockerfile
Labels: size/XS, cla-not-required

#418 🌱 Update golangci-lint to v1.52.2
  .golangci.yml
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  pkg/util/cloudinit/cloudconfig_secret.go
Labels: size/L, cla-not-required

#415 🐛 Fix PodVMOnStretchedSupervisor with WFFC storage class
  pkg/util/cns.go
  test/builder/util.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#422 🐛 Fix inability to get ConfigMap/Secret objs
  controllers/infra/configmap/infra_configmap.go
  controllers/infra/configmap/infra_configmap_controller.go
  controllers/infra/secret/infra_secret_controller.go
  pkg/manager/cache.go
  pkg/manager/manager.go
  pkg/manager/test/cache_test.go
  pkg/manager/test/manager_suite_test.go
  test/builder/test_suite.go
Labels: size/L, cla-not-required

#420 🌱 Misc updates to infra controllers and test labels
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/infra/configmap/infra_configmap_controller_intg_test.go
  controllers/infra/node/infra_node_controller_intg_test.go
  controllers/infra/node/infra_node_controller_suite_test.go
  controllers/infra/secret/infra_secret_controller.go
  controllers/infra/secret/infra_secret_controller_intg_test.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller_intg_test.go
  controllers/virtualmachineclass/v1alpha2/virtualmachineclass_controller_intg_test.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_intg_test.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_suite_test.go
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
  controllers/volume/v1alpha2/volume_controller_intg_test.go
  webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator_intg_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_intg_test.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_intg_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator_intg_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_intg_test.go
Labels: size/M, cla-not-required

#419 :sparkles: Disallow TCP readiness probe under VPC Networking
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#406 :sparkles: Introduce WCP_TKG_Multiple_CL FSS in vm-operator
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/utils/constants.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/M, cla-not-required

#424 ✨ Add client Index on the CnsNodeVmAttachment Spec.NodeUUID
  controllers/volume/v1alpha2/volume_controller.go
  controllers/volume/v1alpha2/volume_controller_unit_test.go
Labels: size/M, cla-not-required

#433 📖 Services and networking
  .markdownlintrc
  docs/concepts/services-networking/README.md
  docs/concepts/services-networking/vm-service.md
  mkdocs.yml
Labels: size/L, cla-not-required

#434 📖 Update docs for v1alpha2
  api/v1alpha1/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/guest.md
  docs/concepts/workloads/vm-example.yaml
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
  docs/start/contrib/submit-change.md
  docs/tutorials/deploy-apps/nfs-server-and-client.md
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/deploy-vm/cloudinit.md
  docs/tutorials/deploy-vm/vappconfig.md
  docs/tutorials/troubleshooting/ip-assignment.md
  docs/tutorials/troubleshooting/publish-vm.md
Labels: size/XXL, cla-not-required

#436 ✨ Sync VMI status to labels
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
  pkg/util/image/image_suite_test.go
  pkg/util/image/status_to_label.go
  pkg/util/image/status_to_label_test.go
Labels: size/L, cla-not-required

#431 ✨ Include resolved net-config in VM status
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: size/XXL, cla-not-required

#437 📖 Update VirtualMachine CRD doc
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/M, cla-not-required

#440 ✨ Bump manager container CPU limit to 750m
  config/wcp/vmoperator/cpu_resources_patch.yaml
Labels: size/XS, cla-not-required

#439 🐛 Better clear VM.Status.Network fields
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: size/L, cla-not-required

#435 🌱 Defer PVC watch in Volume controller until needed
  controllers/volume/v1alpha2/volume_controller.go
  controllers/volume/v1alpha2/volume_controller_unit_test.go
  pkg/context/volume_context.go
  pkg/manager/cache.go
Labels: size/L, cla-not-required

#441 🌱 Handle when the Volume PVC ClaimName is changed
  controllers/volume/v1alpha2/volume_controller.go
  controllers/volume/v1alpha2/volume_controller_unit_test.go
Labels: size/M, cla-not-required

#438 📖 Add encoded ConfigSpec examples
  docs/concepts/workloads/vm-class.md
  pkg/docs/concepts/concepts_suite_test.go
  pkg/docs/concepts/vm-class_test.go
Labels: size/L, cla-not-required

#443 🌱 Remove Simple LB provider
  config/local-vcsim/vcsim-patch.yaml
  controllers/virtualmachineservice/v1alpha2/providers/loadbalancer_provider.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/lb_cloudconfig.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/lb_cloudconfig_test.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_provider.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_provider_test.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/simplelb_suite_test.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/xds_server.go
  controllers/virtualmachineservice/v1alpha2/providers/simplelb/xds_server_test.go
  go.mod
  go.sum
Labels: size/XL, cla-not-required

#417 Mark VirtualMachineService LoadBalancerIP as deprecated
  api/v1alpha1/virtualmachineservice_types.go
  api/v1alpha2/virtualmachineservice_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
Labels: size/S, cla-not-required

#445 📖 VM controller docs / workflows
  docs/concepts/workloads/README.md
  docs/concepts/workloads/vm-controller.md
  mkdocs.yml
Labels: size/M, cla-not-required
