Repository vmware-tanzu/vm-operator, pull requests merged in 2024-01, with the labels that each got.

#334 🐛 Fixes unset/empty write file content in cloudinit
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
  pkg/util/cloudinit/validate/testdata/valid-cloud-config-1.yaml
  pkg/util/cloudinit/validate/validate.go
  pkg/util/cloudinit/validate/validate_test.go
Labels: size/L, cla-not-required

#333 🐛 Fix VirtualMachineImage condition version conversion
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/virtualmachineimage_conversion_test.go
Labels: size/L, cla-not-required

#331 🌱 Add tests for VM Condition version conversion
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
Labels: size/L, cla-not-required

#330 🌱 Add back bootstrap config to VMs in vmE2ETests()
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
Labels: size/L, cla-not-required

#336 🌱 Adds VMI/CVMI test for annotation-status property conversion
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha1/virtualmachineimage_conversion_test.go
Labels: size/M, cla-not-required

#341 🐛 [codegen]: Uses npm ci command to generate schema types
  pkg/util/cloudinit/schema/Dockerfile.quicktype
  pkg/util/cloudinit/schema/Makefile
Labels: size/XS, cla-not-required

#339 🌱 Use v1a2 VM created condition to infer metrics phase
  pkg/metrics2/constants.go
  pkg/metrics2/vmservice_metrics.go
Labels: size/M, cla-not-required

#337 🌱 Add asserts that the NetPlan has the expected IPs
  pkg/vmprovider/providers/vsphere2/network/netplan_test.go
Labels: size/XS, cla-not-required

#338 Use the v1a1 PrereqReady condition to populate v1a2 conditions
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
Labels: size/XL, cla-not-required

#342 🐛 Restore v1a2 Sysprep with vAppConfig in hub-spoke-hub
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
Labels: size/M, cla-not-required

#343 🌱 Fix v1a2 cloud-init example
  api/v1alpha2/testdata/vm-with-cloudinit.yaml
Labels: size/S, cla-not-required

#344 🐛 Do not add the v1a1 Volume controller when v1a2 is enabled
  controllers/volume/controllers.go
Labels: size/XS, cla-not-required

#347 Update NetworkInterface Name field pattern validation
  api/v1alpha2/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/XS, cla-not-required

#348 ✨ Update LinuxPrep and Sysprep Nameservers and SearchDomains
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/vmprovider/providers/vsphere2/network/gosc.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#350 📖 Remove bootstrap doc about automatic LinuxPrep/Sysprep
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/S, cla-not-required

#349 🌱 Use Network Hostname if set for Sysprep computer name
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
Labels: size/S, cla-not-required

#352 🌱 Wait for reconfigure task to complete in v1a2 backup
  api/v1alpha1/virtualmachine_types.go
  pkg/context/backupvirtualmachine_context.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
  pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
Labels: size/XL, cla-not-required

#351 🌱 Update storage policy changes for Pod VM support on stretched supervisor
  config/local/vmoperator/local_env_var_patch.yaml
  config/rbac/role.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  external/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/cnsnodevmattachment/v1alpha1/cnsnodevmattachment_types.go
  external/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/groupversion_info.go
  external/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/storagepolicy/v1alpha1/storagepolicyquota_types.go
  external/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/storagepolicy/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/manager/manager.go
  pkg/util/cns.go
  pkg/vmprovider/providers/vsphere/storage/storageclass.go
  pkg/vmprovider/providers/vsphere2/storage/storageclass.go
  test/builder/fake.go
  test/builder/util.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#355 🌱 Run ci on PRs to the release branches
  .github/workflows/ci.yml
Labels: size/XS, cla-not-required

#353 ✨ Disable DRS PowerOff for VMs with vGPU/Dynamic Direct Path IO devices
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/vmprovider/providers/vsphere/constants/constants.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/constants/constants.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/L, cla-not-required

#354 ✨ Crossport commits for VC 8.0.2p03 release
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha2/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  go.mod
  go.sum
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/devices.go
  pkg/util/hardware_version.go
  pkg/util/hardware_version_test.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_status.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
  test/builder/util.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_intg_test.go
Labels: size/XL, cla-not-required

#357 🐛 Update bootstrap_cloudinit to use MergeExtraConfig
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
Labels: size/XS, cla-not-required

#361 ✨ Guest bootstrap status as condition
  api/v1alpha1/condition_consts.go
  api/v1alpha2/virtualmachine_types.go
  pkg/util/bootstrap_condition.go
  pkg/util/bootstrap_condition_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_status.go
  pkg/vmprovider/providers/vsphere/session/session_vm_status_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Labels: enhancement, size/XXL, cla-not-required

#358 ✨ Set v1a2 FSS to true by default
  config/local/vmoperator/local_env_var_patch.yaml
  controllers/contentlibrary/v1alpha1/contentlibraryitem/contentlibraryitem_controller_suite_test.go
  controllers/virtualmachinepublishrequest/v1alpha1/virtualmachinepublishrequest_controller_suite_test.go
  pkg/config/default.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#359 ✨ Set enabled FSSs to true by default
  config/local/vmoperator/local_env_var_patch.yaml
Labels: size/S, cla-not-required

#356 🌱Run ci workflows for PR created on release branches
  .github/workflows/ci.yml
Labels: duplicate, size/XS, cla-not-required

#364 ✨ Created-at annotations
  pkg/config/config.go
  pkg/config/default.go
  pkg/constants/constants.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#366 🌱 Remove dup validate instance stoarge call in VM webhook update
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
Labels: size/XS, cla-not-required

#369 🐛 Drop validating annotations added by mutation webhook upon VM creation
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#370 🌱 Clean up how Sysprep w/ vAppConfig is restored
  api/v1alpha1/virtualmachine_conversion.go
Labels: size/XS, cla-not-required

#373 🌱 Skip VM Service B/R workflow for TKG node VMs
  pkg/util/kube/vm.go
  pkg/util/kube/vm_test.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  test/builder/vcsim_test_context.go
Labels: size/L, cla-not-required

#371 🌱 Set HW Version in CreateConfigSpec()
  pkg/util/devices.go
  pkg/util/devices_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/virtualmachine_suite_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
Labels: size/XL, cla-not-required

#376 🐛 Remove singular role resource names
  config/rbac/role.yaml
  controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
  webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
Labels: size/S, cla-not-required
