Repository vmware-tanzu/vm-operator, pull requests merged in 2024-04, with the labels that each got.

#447 ✨ UpdateExtraConfig for powered on VMs, iterate list once
  pkg/util/configspec.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
Labels: size/L, cla-not-required

#448 ✨ Remove VM Class as Config (DnD too) FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/devices.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create_contentlibrary.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
  test/builder/vcsim_test_context.go
Labels: size/XL, cla-not-required

#446 ⚠️ Remove need for VM Image in Update path
  config/local-vcsim/vcsim-patch.yaml
  pkg/vmprovider/providers/vsphere2/constants/constants.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Labels: size/L, cla-not-required

#452 ✨ Remove sysprep FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#450 ✨ Remove image registry FSS
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha2/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_suite_test.go
  controllers/controllers.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_suite_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  test/builder/test_suite.go
  test/builder/util.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_unit_test.go
Labels: size/L, cla-not-required

#451 ✨ Remove unified TKG FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#453 ✨ Remove namespaced VM Class FSS
  api/v1alpha1/virtualmachineclass_types.go
  api/v1alpha2/virtualmachineclass_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
  test/builder/test_suite.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_intg_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_intg_test.go
Labels: size/M, cla-not-required

#454 ✨ Remove v1alpha2 FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/contentlibrary/controllers.go
  controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_suite_test.go
  controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_suite_test.go
  controllers/virtualmachine/controllers.go
  controllers/virtualmachine/v1alpha2/virtualmachine_controller_suite_test.go
  controllers/virtualmachineclass/controllers.go
  controllers/virtualmachineclass/v1alpha2/virtualmachineclass_controller_suite_test.go
  controllers/virtualmachinepublishrequest/controllers.go
  controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_suite_test.go
  controllers/virtualmachineservice/controllers.go
  controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_suite_test.go
  controllers/virtualmachinesetresourcepolicy/controllers.go
  controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_suite_test.go
  controllers/virtualmachinewebconsolerequest/controllers.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/patch/patch_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_suite_test.go
  controllers/volume/controllers.go
  controllers/volume/v1alpha2/volume_controller_suite_test.go
  hack/deploy-local.sh
  main.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/manager/init/init_providers.go
  pkg/manager/manager.go
  test/builder/test_suite.go
  test/builder/util.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_suite_test.go
  webhooks/virtualmachine/webhooks.go
  webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_suite_test.go
  webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_suite_test.go
  webhooks/virtualmachineclass/webhooks.go
  webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_suite_test.go
  webhooks/virtualmachinepublishrequest/webhooks.go
  webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_suite_test.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_suite_test.go
  webhooks/virtualmachineservice/webhooks.go
  webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_suite_test.go
  webhooks/virtualmachinesetresourcepolicy/webhooks.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_suite_test.go
  webhooks/virtualmachinewebconsolerequest/webhooks.go
Labels: size/L, cla-not-required

#457 🌱 Reintroduce FSS flags for internal testing
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
Labels: size/M, cla-not-required

#456 🌱 Add label to network interface CR for its VM name
  pkg/vmprovider/providers/vsphere2/network/network.go
  pkg/vmprovider/providers/vsphere2/network/network_test.go
Labels: size/S, cla-not-required

#459 ✨ Mod updates for vulncheck
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, cla-not-required

#458 🐛 Fix UpdateConfigSpecExtraConfig() when reconciling VM with vGPU/DDPIO
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
Labels: size/M, cla-not-required

#464 🐛 Remove dup FSS_WCP_NAMESPACED_VM_CLASS FSS env var from manager patch
  config/wcp/vmoperator/manager_env_var_patch.yaml
Labels: size/XS, cla-not-required

#465 🐛 Remove dup FSS_WCP_NAMESPACED_VM_CLASS FSS env var from manager patch…
  config/wcp/vmoperator/manager_env_var_patch.yaml
Labels: size/XS, cla-not-required

#455 ✨ ConfigSpec by value
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/vmprovider/providers/vsphere2/placement/cluster_placement.go
  pkg/vmprovider/providers/vsphere2/placement/zone_placement.go
  pkg/vmprovider/providers/vsphere2/placement/zone_placement_test.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
  pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create_clone.go
  pkg/vmprovider/providers/vsphere2/vmlifecycle/create_contentlibrary.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
  pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
Labels: size/L, cla-not-required

#466 🐛Use IsDNS1035Label for VirtualMachineService validations
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
  webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_unit_test.go
Labels: size/S, cla-not-required

#460 :seedling: Add ExtraConfig Key, Label, Condition and validation for break glass override
  api/v1alpha2/virtualmachine_types.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
  webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#471 ✨ Single test target / workflow
  .github/workflows/ci.yml
  Makefile
Labels: size/M, cla-not-required

#449 🌱 Redact sensitive fields in bootstrap config and customization specs
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_test.go
Labels: size/L, cla-not-required

#470 ✨ Introduce vm.spec.image reference
  .golangci.yml
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/vmlifecycle/create_clone.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  pkg/util/vmopv1/vmopv1_suite_test.go
  test/builder/test_suite.go
  test/builder/utila2.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XXL, cla-not-required

#474 🐛 GoVmomi c385285
  go.mod
  go.sum
Labels: size/S, cla-not-required

#475 🌱 Update deprecated GitHub actions
  .github/workflows/ci.yml
Labels: size/S, cla-not-required

#476 🌱 Combine test and coverage actions
  .github/workflows/ci.yml
Labels: size/M, cla-not-required

#477 🌱 Update gnotify setup-python action
  .github/workflows/gnotify.yml
Labels: size/XS, cla-not-required

#480 ✨ GuestInfo prober fetches required props only
  pkg/prober/probe/guestinfo.go
  pkg/prober/probe/guestinfo_test.go
  pkg/prober/probe/probe.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, cla-not-required

#478 :seedling: Introduce FSS for workload management of VMs using Kubernetes patterns
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#482 🌱 Introduce FSS for ISO support
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/builder/auth.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#463 🐛 Specify BIOS and instance UUIDs when creating VM
  api/go.mod
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_bootstrap_types.go
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/vcenter/getvm.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#469 :sparkles: Implement admin override to pause VM reconciliation
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha3/virtualmachine_types.go
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine_controller_unit_test.go
  controllers/volume/volume_controller.go
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/util/vsphere/vm/vm.go
  pkg/util/vsphere/vm/vm_test.go
Labels: size/L, cla-not-required

#490 🐛 Fix conversion, fix Cloud-Init ID, add conv tests
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
Labels: size/L, cla-not-required

#491 🌱 GitHub action verify-codegen checks conversions
  hack/verify-codegen.sh
Labels: size/M, cla-not-required
