Repository vmware-tanzu/vm-operator, pull requests merged in 2024-10, with the labels that each got.

#714 :sparkles: Define new unified storage quota management plugin webhook
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_intg_test.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_suite_test.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
  webhooks/unifiedstoragequota/webhooks.go
  webhooks/webhooks.go
Labels: size/XXL, cla-not-required

#726 🌱 SetAnnotation() after pause annotation rename conversion
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
Labels: size/M

#727 🌱 Use KeyWithValue() for conversation annotation testing
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion_test.go
Labels: size/XS

#729 🌱 Move non-API backup symbols to pkg/backup
  .golangci.yml
  Makefile
  api/backup/backup.go
  api/backup/zz_generated.deepcopy.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha3/virtualmachine_types.go
  go.mod
  pkg/backup/api/backup_types.go
  pkg/backup/api/go.mod
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#701 🌱 Add image type label in VMI and CVMI objects
  api/v1alpha3/virtualmachineimage_types.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/utils/utils.go
  pkg/util/image/status_to_label.go
  pkg/util/image/status_to_label_test.go
Labels: size/L, cla-not-required

#732 🐛 Skip resizing ISO VM boot disk
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha3.md
  pkg/providers/vsphere/session/session_vm.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmlifecycle/create_clone.go
Labels: size/M

#736 :sparkles: Add ValidatingWebhookConfiguration controller
  config/rbac/role.yaml
  controllers/infra/controllers.go
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller.go
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_intg_test.go
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_suite_test.go
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_unit_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  pkg/util/kube/spq/spq.go
  pkg/util/kube/spq/spq_test.go
Labels: size/XL

#733 ✨ Reconcile VMs on async signal
  config/rbac/role.yaml
  controllers/infra/controllers.go
  controllers/infra/zone/zone_controller.go
  controllers/infra/zone/zone_controller_suite_test.go
  controllers/infra/zone/zone_controller_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/constants/testlabels/test_labels.go
  pkg/context/generic/generic_context.go
  pkg/context/generic/generic_context_test.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/vmprovider.go
  pkg/util/kube/cource/cource_context.go
  pkg/util/kube/cource/cource_context_test.go
  pkg/util/vsphere/client/client.go
  pkg/util/vsphere/watcher/watcher.go
  pkg/util/vsphere/watcher/watcher_context.go
  pkg/util/vsphere/watcher/watcher_context_test.go
  pkg/util/vsphere/watcher/watcher_suite_test.go
  pkg/util/vsphere/watcher/watcher_test.go
  services/services.go
  services/vm-watcher/vm_watcher_service.go
  services/vm-watcher/vm_watcher_service_suite_test.go
  services/vm-watcher/vm_watcher_service_test.go
  test/builder/test_suite.go
  test/builder/vcsim_test_context.go
  test/testutil/util.go
Labels: size/XXL

#739 🌱 Remove lock on vm watcher
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/infra/zone/zone_controller.go
  pkg/util/vsphere/watcher/watcher.go
  pkg/util/vsphere/watcher/watcher_context.go
  pkg/util/vsphere/watcher/watcher_context_test.go
Labels: size/L

#738 ✨ Supervisor Capabilities
  .golangci.yml
  Makefile
  config/crd/external-crds/iaas.vmware.com_capabilities.yaml
  config/rbac/role.yaml
  controllers/infra/capability/configmap/configmap_capability_controller.go
  controllers/infra/capability/configmap/configmap_capability_controller_suite_test.go
  controllers/infra/capability/configmap/configmap_capability_controller_test.go
  controllers/infra/capability/controllers.go
  controllers/infra/capability/crd/crd_capability_controller.go
  controllers/infra/capability/crd/crd_capability_controller_suite_test.go
  controllers/infra/capability/crd/crd_capability_controller_test.go
  controllers/infra/capability/exit/exit.go
  controllers/infra/capability/infra_capability_controller_intg_test.go
  controllers/infra/capability/infra_capability_controller_suite_test.go
  controllers/infra/capability/infra_capability_controller_unit_test.go
  external/capabilities/api/v1alpha1/capabilities_types.go
  external/capabilities/api/v1alpha1/doc.go
  external/capabilities/api/v1alpha1/groupversion_info.go
  external/capabilities/api/v1alpha1/zz_generated.deepcopy.go
  external/capabilities/go.mod
  external/capabilities/go.sum
  go.mod
  go.sum
  main.go
  pkg/config/capabilities/capabilities_suite_test.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/manager/manager.go
  test/builder/fake.go
Labels: size/XXL

#737 Honor PVC requested zonal constraints for VM placement
  go.mod
  pkg/providers/vsphere/placement/cluster_placement.go
  pkg/providers/vsphere/placement/zone_placement.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/storage/storage.go
  pkg/providers/vsphere/storage/storage_suite_test.go
  pkg/providers/vsphere/storage/storage_test.go
  pkg/providers/vsphere/storage/storageclass.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/kube/storage.go
  pkg/util/kube/storage_test.go
Labels: size/XL

#734 🐛 Assign CD-ROMs to correct controller unit numbers
  go.mod
  go.sum
  pkg/providers/vsphere/virtualmachine/cdrom.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
Labels: size/L

#728 :seedling: Add ValidatingWebhookConfiguration for storage quota webhook
  config/webhook/kustomization.yaml
  config/webhook/storage_quota_webhook_configuration.yaml
Labels: size/M

#740 Include pkg/backup/api in make modules target
  Makefile
Labels: size/XS

#742 🐛 BYOK: Add vm controller permission for watching encryptionclasses
  config/rbac/role.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
Labels: size/XS

#745 🌱 Change EncryptionClass API group
  config/crd/external-crds/encryption.vmware.com_encryptionclasses.yaml
  config/rbac/role.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  external/byok/api/v1alpha1/doc.go
  external/byok/api/v1alpha1/groupversion_info.go
Labels: size/M

#746 🌱 Import correct encryption CRD in kustomize
  config/default/kustomization.yaml
Labels: size/XS

#747 📖 Clarify storage class requirement for crypto.encryptionClassName API
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha3.md
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/XS

#750 🐛 Fix panic when crypto err does not include fault
  go.mod
  go.sum
  pkg/vmconfig/crypto/crypto_reconciler_post_test.go
Labels: size/S

#749 🌱 Rename resize related condition to ClassConfigurationSynced
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
Labels: size/M

#748 🌱 Remove use of deprecated kustomize symbols
  config/certmanager/certificate.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_clustervirtualmachineimages.yaml
  config/crd/patches/cainjection_in_virtualmachineclasses.yaml
  config/crd/patches/cainjection_in_virtualmachineimages.yaml
  config/crd/patches/cainjection_in_virtualmachinepublishrequests.yaml
  config/crd/patches/cainjection_in_virtualmachinereplicasets.yaml
  config/crd/patches/cainjection_in_virtualmachines.yaml
  config/crd/patches/cainjection_in_virtualmachineservices.yaml
  config/crd/patches/cainjection_in_virtualmachinesetresourcepolicies.yaml
  config/crd/patches/cainjection_in_virtualmachinewebconsolerequests.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_leader_election_id_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/local-vcsim/kustomization.yaml
  config/local/kustomization.yaml
  config/local/vmoperator/kustomization.yaml
  config/rbac/auth_proxy_service.yaml
  config/replacements/kustomization.yaml
  config/wcp-no-configmap/kustomization.yaml
  config/wcp/kustomization.yaml
  config/wcp/vmoperator/kustomization.yaml
  config/wcp/vmoperator/service_metrics_port_patch.yaml
  config/web-console-validator/web_console_validator.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  config/webhook/webhookcainjection_patch.yaml
Labels: size/XL

#751 🌱 Set default EncryptionClass on VM when available
  pkg/util/kube/crypto.go
  pkg/util/kube/crypto_test.go
  pkg/util/kube/storage.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_suite_test.go
Labels: size/XL

#752 🌱 Support kustomize-wcp
  Makefile
Labels: size/S

#753 🌱 GitHub action to verify WCP manifests
  .github/workflows/ci.yml
  Makefile
  hack/deploy-local-certmanager.sh
  hack/deploy-local.sh
Labels: size/L

#754 ✨ Support PVCs with BYOK
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_intg_test.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  pkg/providers/vsphere/constants/constants.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#758 🌱 Remove vestigial kustomize var refs
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomizeconfig.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/webhook/kustomizeconfig.yaml
Labels: size/M, cla-not-required

#755 🌱 Check image ready condition before mounting ISO
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/cdrom.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
  test/builder/dummies.go
Labels: size/L

#731 :seedling: Upgrade Go to 1.23 to support TLS 1.3
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/backup/api/go.mod
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/util/kube/spq/spq_test.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
  test/builder/unit_test_context.go
  test/builder/vcsim_test_context.go
Labels: size/L

#756 🌱 Fixes for Bring Your Own Key (BYOK) provider
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/vmconfig/crypto/crypto_reconciler.go
  pkg/vmconfig/crypto/crypto_reconciler_post.go
  pkg/vmconfig/crypto/crypto_reconciler_post_test.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
  pkg/vmconfig/crypto/internal/crypto_reconciler_context.go
Labels: size/XXL

#759 🐛 Fix validate classless vm on update
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#761 :bug: Fix typo in kubebuilder annotation for manager ClusterRole
  config/rbac/role.yaml
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller.go
Labels: size/XS, cla-not-required

#764 🐛 Fix how crypto detects device sans policy
  pkg/util/kube/storage.go
  pkg/util/kube/storage_test.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
Labels: size/L, cla-not-required

#760 :seedling: Refactor unifiedstoragequota validating webhook unit tests to use Ginkgo
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_intg_test.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_suite_test.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
Labels: size/XXL, cla-not-required

#768 :bug: Correctly handle optional, nillable path in CEL expression
  config/webhook/storage_quota_webhook_configuration.yaml
Labels: size/XS, cla-not-required

#767 🌱 Use fake client interceptor funcs for insufficient quota PVC test
  controllers/virtualmachine/volume/volume_controller_unit_test.go
Labels: size/M, cla-not-required

#766 🌱 Use struct assignment to copy bootstrap data
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/XS, cla-not-required

#771 🌱 Watch crypto state
  pkg/util/vsphere/watcher/watcher.go
Labels: size/XS, cla-not-required

#769 🌱 Avoid endless retry if StorageClass does not have policy ID
  controllers/storageclass/storageclass_controller.go
  controllers/storageclass/storageclass_controller_unit_test.go
Labels: size/S, cla-not-required

#770 🌱 Aggregate CreateOrPatch errors during StoragePolicyQuota reconcile
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
Labels: size/S, cla-not-required

#772 📖 Doc updates
  docs/concepts/workloads/vm.md
Labels: size/L, cla-not-required

#774 🐛 Plumb logger into async VM watcher service
  services/vm-watcher/vm_watcher_service.go
Labels: size/XS, cla-not-required

#773 🌱 Fetch only Host Summary.Hardware.cpuMhz for min CPU calculation
  pkg/providers/vsphere/vcenter/cluster.go
Labels: size/XS, cla-not-required

#778 🐛 Update async logging / fix NPE in crypt reconciler
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  pkg/util/vsphere/watcher/watcher.go
  pkg/vmconfig/crypto/crypto_reconciler_post.go
  pkg/vmconfig/crypto/crypto_reconciler_post_test.go
  services/vm-watcher/vm_watcher_service.go
  services/vm-watcher/vm_watcher_service_test.go
Labels: size/M, cla-not-required

#779 🌱 Add capabilities scheme to init features client scheme
  main.go
  pkg/config/capabilities/capabilties.go
Labels: size/S, cla-not-required

#780 🌱 Remove duplicate vmopv1.AddToScheme() call
  pkg/manager/manager.go
Labels: size/XS, cla-not-required

#763 🌱 Disallow PVCs with WaitForFirstConsumer StorageClass
  controllers/virtualmachine/volume/volume_controller.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#784 🐛 deps: bump govmomi to fix vcsim PropertyCollector race
  go.mod
  go.sum
Labels: size/XS, cla-not-required

#783 ✨ Support building cross-arch images
  .github/workflows/ci.yml
  Makefile
  hack/build-container.sh
Labels: size/L, cla-not-required

#785 🐛 byok: validate encryption class keyID if specified
  go.mod
  go.sum
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
Labels: size/M, cla-not-required

#787 ✨ Unifiy build process up and downstream
  .dockerignore
  .github/workflows/ci.yml
  Dockerfile
  Makefile
  hack/build-container.sh
Labels: size/L, cla-not-required

#776 :seedling: Clean up duplicate nameservers when deployed with multiple NICs
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/util/network.go
  pkg/util/network_test.go
Labels: size/M, cla-not-required
