Repository vmware-tanzu/vm-operator, pull requests merged in 2024-12, with the labels that each got.

#811 🌱 OVF Cache Package
  main.go
  pkg/context/fake/fake_controller_manager_context.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
  pkg/util/ovfcache/internal/ovfcache_internal.go
  pkg/util/ovfcache/internal/ovfcache_internal_suite_test.go
  pkg/util/ovfcache/internal/ovfcache_internal_test.go
  pkg/util/ovfcache/ovfcache.go
  pkg/util/ovfcache/ovfcache_suite_test.go
  pkg/util/ovfcache/ovfcache_test.go
  test/builder/unit_test_context.go
  test/builder/vcsim_test_context.go
Labels: size/XL, cla-not-required

#813 🐛 Fix panic in controllers missing ovfcache
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_suite_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_suite_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
  pkg/util/ovfcache/internal/ovfcache_internal.go
  pkg/util/ovfcache/internal/ovfcache_internal_test.go
  pkg/util/ovfcache/ovfcache.go
Labels: size/L, cla-not-required

#797 🌱 Support for full netplan spec
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  hack/quicktype/.gitignore
  hack/quicktype/Dockerfile
  hack/quicktype/Makefile
  hack/quicktype/package-lock.json
  hack/quicktype/package.json
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/network/netplan_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/util/cloudinit/schema/.gitignore
  pkg/util/cloudinit/schema/Dockerfile.quicktype
  pkg/util/cloudinit/schema/Makefile
  pkg/util/cloudinit/schema/README.md
  pkg/util/netplan/netplan.go
  pkg/util/netplan/netplan_suite_test.go
  pkg/util/netplan/netplan_test.go
  pkg/util/netplan/schema/.gitignore
  pkg/util/netplan/schema/Dockerfile
  pkg/util/netplan/schema/Makefile
  pkg/util/netplan/schema/README.md
  pkg/util/netplan/schema/main.rs
  pkg/util/netplan/schema/netplan.go
  pkg/util/netplan/schema/schema.json
Labels: size/XXL, cla-not-required

#810 🌱 Use unique finalizer name for infra Zone controller
  controllers/infra/zone/zone_controller.go
Labels: size/XS

#817 🐛 Wait on vAppConfig during async create
  pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig_test.go
Labels: size/M, cla-not-required

#814 :seedling: Allow imported and registered VMs to skip image validation checks on Create/Update
  api/v1alpha3/virtualmachine_types.go
  pkg/util/annotations/helpers.go
  pkg/util/annotations/helpers_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#818 🐛 Remove Inventory path fallback for GetVM
  pkg/providers/vsphere/vcenter/getvm.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vmprovider.go
Labels: size/L, cla-not-required

#819 🌱 Remove WCP_Simplified_Enablement FSS
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_unit_test.go
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/util/kube/proxyaddr/proxy_address.go
  pkg/util/kube/proxyaddr/proxy_address_test.go
Labels: size/M, cla-not-required

#822 :bug: Do not invoke StoragePolicyQuota Validating Webhook for imageless VMs
  config/webhook/storage_quota_webhook_configuration.yaml
Labels: size/XS, cla-not-required

#820 🐛 Add VirtualMachineWebConsoleRequest in web-console-validator
  cmd/web-console-validator/main.go
  controllers/virtualmachinewebconsolerequest/controllers.go
  controllers/virtualmachinewebconsolerequest/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/webconsolerequest_suite_test.go
  controllers/virtualmachinewebconsolerequest/webconsolerequest_unit_test.go
  pkg/webconsolevalidation/server.go
  pkg/webconsolevalidation/server_test.go
  webhooks/virtualmachinewebconsolerequest/v1alpha2/webhooks.go
  webhooks/virtualmachinewebconsolerequest/validation/webconsolerequest_validator.go
  webhooks/virtualmachinewebconsolerequest/validation/webconsolerequest_validator_intg_test.go
  webhooks/virtualmachinewebconsolerequest/validation/webconsolerequest_validator_suite_test.go
  webhooks/virtualmachinewebconsolerequest/validation/webconsolerequest_validator_unit_test.go
  webhooks/virtualmachinewebconsolerequest/webhooks.go
Labels: size/L, cla-not-required

#815 🌱 Remove disk related backup field from ExtraConfig when empty
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/L, cla-not-required

#824 🐛 Update GoVmomi to b1027ba34d97 from main
  go.mod
  go.sum
  pkg/providers/vsphere/client/client_test.go
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/util/ovfcache/internal/ovfcache_internal_test.go
  pkg/util/vsphere/client/client_test.go
Labels: size/M, cla-not-required

#825 🌱 Do not hardcode PVC UUID in backup test
  go.mod
  go.sum
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/S, cla-not-required

#828 🌱 Fix race in WebConsoleRequest controller tests
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
Labels: size/S, cla-not-required

#831 ✨ Mark v1alpha1 as deprecated
  api/v1alpha1/contentlibraryprovider_types.go
  api/v1alpha1/contentsource_types.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/virtualmachineclass_types.go
  api/v1alpha1/virtualmachineclassbinding_types.go
  api/v1alpha1/virtualmachineimage_types.go
  api/v1alpha1/virtualmachinepublishrequest_types.go
  api/v1alpha1/virtualmachineservice_types.go
  api/v1alpha1/virtualmachinesetresourcepolicy_types.go
  api/v1alpha1/webconsolerequest_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/crd/bases/vmoperator.vmware.com_contentsources.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
Labels: size/S, cla-not-required

#830 🌱 Do not CBLO if VM watcher service fails
  services/vm-watcher/vm_watcher_service.go
  services/vm-watcher/vm_watcher_service_test.go
Labels: size/M, cla-not-required

#827 🐛 Fix potential VM validation webhook NPE for Spec.Network
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#833 🐛 fix: bump govmomi to include pbm client authentication fix
  go.mod
  go.sum
Labels: size/XS, cla-not-required

#829 :seedling: Introduce a new annotation to identify failed over VMs
  api/v1alpha3/virtualmachine_types.go
  pkg/backup/api/backup_types.go
  pkg/util/annotations/helpers.go
  pkg/util/annotations/helpers_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#826 ✨ Add option for CloudInit to default to global NS and SearchDomains
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_bootstrap_types.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_bootstrap_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#836 🌱 Refactor chanErr creation & consumption for async create VM workflow
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/L, cla-not-required

#835 🌱 Remove stale envoyproxy go.mod replace entries
  go.mod
Labels: size/XS, cla-not-required

#834 🌱 Use errors.Is() to silence lint warnings
  .golangci.yml
  cmd/web-console-validator/main.go
  controllers/infra/zone/zone_controller.go
  controllers/util/encoding/encoding.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/util/vsphere/vm/power_state.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
  test/builder/util.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
Labels: size/M, cla-not-required

#837 🐛 Skip ISO images in unified storage quota validator
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
Labels: size/S, cla-not-required

#838 :seedling: Use annotation helpers from upstream metav1 instead of custom ones
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/volume/volume_controller.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/annotations/helpers.go
  pkg/util/annotations/helpers_suite_test.go
  pkg/util/annotations/helpers_test.go
  pkg/util/paused/paused.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#823 ✨ Fast Deploy (Experimental)
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/vsphere/client/client_test.go
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/placement/cluster_placement.go
  pkg/providers/vsphere/placement/zone_placement.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary_linked_clone.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/nil.go
  pkg/util/nil_test.go
  pkg/util/vmopv1/image.go
  pkg/util/vmopv1/image_test.go
  pkg/util/vsphere/client/client_test.go
  pkg/util/vsphere/library/item_cache.go
  pkg/util/vsphere/library/item_cache_test.go
  pkg/util/vsphere/library/item_sync.go
  pkg/util/vsphere/library/item_sync_test.go
  pkg/util/vsphere/library/library_suite_test.go
Labels: size/XXL, cla-not-required

#842 🐛 Fix lint error about err checking
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary_linked_clone.go
Labels: size/XS, cla-not-required

#841 🐛 Preserve crypto status in managed vols (PVC)
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
Labels: size/M, cla-not-required

#843 📖 Add docs for CD-ROM and ISO VM deployment workflow
  docs/concepts/workloads/vm.md
  docs/ref/proj/docs.md
  docs/tutorials/deploy-vm/README.md
  docs/tutorials/deploy-vm/iso.md
  mkdocs.yml
Labels: size/L, cla-not-required

#845 📖 Fix broken link in the deploy VM doc
  docs/tutorials/deploy-vm/README.md
Labels: size/XS, cla-not-required

#840 ✨ Conditions helper & refactor
  pkg/conditions/conditions.go
  pkg/conditions/conditions_suite_test.go
  pkg/conditions/conditions_test.go
  pkg/conditions/getter.go
  pkg/conditions/getter_test.go
  pkg/conditions/merge.go
  pkg/conditions/merge_strategies.go
  pkg/conditions/merge_strategies_test.go
  pkg/conditions/merge_test.go
  pkg/conditions/patch_test.go
  pkg/conditions/setter.go
  pkg/conditions/setter_test.go
  pkg/conditions/unstructured_test.go
  pkg/patch/patch.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
Labels: size/XXL, cla-not-required

#844 :bug: Use NSX-T LB for VPC networking when lb unspecified
  controllers/virtualmachineservice/virtualmachineservice_controller.go
Labels: size/XS, cla-not-required
