Repository vmware-tanzu/vm-operator, pull requests merged in 2024-11, with the labels that each got.

#789 🐛 Set bus number when adding SATA controllers for CD-ROM assignment
  go.mod
  go.sum
  pkg/providers/vsphere/virtualmachine/cdrom.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
Labels: size/L, cla-not-required

#791 🐛 Update VM API spec.bootstrap.sysprep fields
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/sysprep/conversion/v1alpha2/sysprep_conversion.go
  api/v1alpha2/sysprep/conversion/v1alpha3/sysprep_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha3/sysprep/sysprep.go
  api/v1alpha3/sysprep/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/sysprep/secret.go
  pkg/providers/vsphere/sysprep/secret_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep_test.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/L, cla-not-required

#794 🌱 Minimum version selection
  Makefile
  api/go.mod
  external/byok/go.mod
  external/byok/go.sum
  external/capabilities/go.mod
  external/capabilities/go.sum
  external/storage-policy-quota/api/v1alpha1/groupversion_info.go
  external/storage-policy-quota/api/v1alpha1/storagepolicyquota_types.go
  external/storage-policy-quota/api/v1alpha1/storagepolicyusage_types.go
  external/storage-policy-quota/api/v1alpha1/storagequota_types.go
  external/storage-policy-quota/api/v1alpha1/zz_generated.deepcopy.go
  external/storage-policy-quota/go.mod
  external/storage-policy-quota/go.sum
  external/tanzu-topology/api/v1alpha1/availability_zone.go
  external/tanzu-topology/api/v1alpha1/groupversion_info.go
  external/tanzu-topology/api/v1alpha1/vsphere_zone.go
  external/tanzu-topology/api/v1alpha1/zone.go
  external/tanzu-topology/api/v1alpha1/zz_generated.deepcopy.go
  external/tanzu-topology/go.mod
  external/tanzu-topology/go.sum
  go.sum
  pkg/backup/api/go.mod
  pkg/constants/testlabels/go.mod
Labels: size/L, cla-not-required

#735 🐛 Use API Server DNS Names by default when logging into VM Web Console
  .golangci.yml
  Makefile
  config/crd/external-crds/appplatform.vmware.com_supervisorproperties.yaml
  config/rbac/supervisor_properties_role.yaml
  config/rbac/supervisor_properties_role_binding.yaml
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_unit_test.go
  external/appplatform/api/v1alpha1/doc.go
  external/appplatform/api/v1alpha1/register.go
  external/appplatform/api/v1alpha1/supervisorprops_types.go
  external/appplatform/api/v1alpha1/zz_generated.deepcopy.go
  external/appplatform/go.mod
  external/appplatform/go.sum
  go.mod
  pkg/manager/manager.go
  pkg/util/kube/proxyaddr/proxy_address.go
  pkg/util/kube/proxyaddr/proxy_address_test.go
  pkg/util/kube/proxyaddr/proxyaddr_suite_test.go
  test/builder/fake.go
Labels: size/XL

#796 🌱Remove BackupUpToDate Condition from the backup data
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/XS, cla-not-required

#800 📖 Document supported hardware
  docs/concepts/workloads/vm.md
Labels: size/XS, cla-not-required

#798 📖 Document ClassConfigurationSynced condition
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
Labels: size/S, cla-not-required

#802 🌱 Use VAPI ActivationID with DeployOVF
  pkg/providers/vsphere/virtualmachine/publish.go
  pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
  pkg/util/vapi.go
Labels: size/M, cla-not-required

#795 🌱 Better handle bound PVC placement with multiple accessible zones
  pkg/util/kube/storage.go
  pkg/util/kube/storage_test.go
Labels: size/M, cla-not-required

#801 ✨ Deprecate ProbeManager for non-TCP probes
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/record/recorder_context.go
  pkg/record/recorder_context_test.go
  pkg/util/vsphere/watcher/watcher.go
  test/builder/vcsim_test_context.go
Labels: size/XXL, cla-not-required

#781 ✨ Support async create VM
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_intg_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
Labels: size/XXL, cla-not-required

#803 :seedling: Allow SRM to change network of a registered VM for test failover
  pkg/backup/api/backup_types.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#804 🌱 Upgrade submodules to Go 1.17+
  external/byok/go.mod
  external/byok/go.sum
  external/capabilities/go.mod
  external/capabilities/go.sum
  external/ncp/go.mod
  external/ncp/go.sum
  external/storage-policy-quota/go.mod
  external/storage-policy-quota/go.sum
  external/tanzu-topology/go.mod
  external/tanzu-topology/go.sum
  go.sum
Labels: size/M, cla-not-required

#806 🐛 Fix RBAC for SupervisorProperties CRD
  Makefile
  config/rbac/role.yaml
  config/rbac/supervisor_properties_role.yaml
  config/rbac/supervisor_properties_role_binding.yaml
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_controller.go
  pkg/util/kube/proxyaddr/proxy_address.go
Labels: size/M, cla-not-required

#807 🐛 Set min HW version when VM has vTPM
  pkg/constants/constants.go
  pkg/providers/vsphere/placement/cluster_placement.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
Labels: size/M, cla-not-required

#809 🌱 Remove old A2 function suffix
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vcenter/resourcepool_test.go
  test/builder/vcsim_test_context.go
Labels: size/S, cla-not-required
