Repository vmware-tanzu/vm-operator, pull requests merged in 2024-08, with the labels that each got.

#648 🌱 resize: Remove DevOps overrides from CPU/Memory resize
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
Labels: size/L, cla-not-required

#642 🌱 Add FSS_WCP_VMSERVICE_INCREMENTAL_RESTORE
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#646 📖 Update docs for recent VM Status storage changes
  docs/ref/api/v1alpha3.md
Labels: cla-not-required

#651 ✨ resize: handle CPU and memory reservations/limits for limited resize
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#644 🌱 Change APIGroup for VPC
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion_test.go
  config/rbac/role.yaml
  controllers/virtualmachine/virtualmachine_controller.go
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  test/builder/fake.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/M, cla-not-required

#650 :seedling: Update vcsim tests under WCP_Workload_Domain_Isolation
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/vcenter/folder_test.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vcenter/resourcepool_test.go
  pkg/providers/vsphere/vmprovider_resourcepolicy_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/vcsim_test_context.go
Labels: size/XL, cla-not-required

#647 :sparkles: Update VirtualMachineImage and ClusterVirtualMachineImage resources to report disk information
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachineimage_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  go.mod
  go.sum
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/contentlibrary/content_library_utils_test.go
  pkg/providers/vsphere/vmprovider_test.go
Labels: size/M, cla-not-required

#657 🐛 Put StoragePolicyQuota controller behind FSS
  controllers/controllers.go
Labels: size/XS, cla-not-required

#658 🐛 Set CPU/Mem Allocation Shares to default normal value
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/S, cla-not-required

#656 🐛 Sync subscribed ISO library item before connecting CD-ROM
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/util/vsphere/vm/cdrom.go
  pkg/util/vsphere/vm/cdrom_test.go
  pkg/util/vsphere/vm/suite_test.go
  test/builder/dummies.go
  test/builder/vcsim_test_context.go
Labels: size/L, cla-not-required

#661 🌱 Add FSS_STORAGE_QUOTA_M2 to manifests
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
Labels: size/XS, cla-not-required

#652 📖 Update vApp template function names for v1a3
  docs/concepts/workloads/guest.md
Labels: size/S, cla-not-required

#653 📖 Update docs for v1a2+ power state enums
  docs/concepts/workloads/vm.md
Labels: size/S, cla-not-required

#654 ✨ Perennial properties
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/session/session.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
  pkg/util/vmopv1/resize_overwrite.go
  pkg/util/vmopv1/resize_overwrite_test.go
  pkg/util/vsphere/vm/guest_id.go
  pkg/util/vsphere/vm/guest_id_test.go
Labels: size/XL, cla-not-required

#664 🌱 Update vmservice.namespace|name to be single field
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/util/vmopv1/resize_overwrite.go
  pkg/util/vmopv1/resize_overwrite_test.go
Labels: size/L, cla-not-required

#659 🐛 Update CD-ROM API fields and related webhook code
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha3.md
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/util/vmopv1/resize_overwrite_test.go
  pkg/util/vsphere/vm/cdrom.go
  pkg/util/vsphere/vm/cdrom_test.go
  test/builder/dummies.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#665 🐛 ExtraConfig keys as OptionVals when getting props / prober
  pkg/prober/probe/guestinfo.go
  pkg/prober/probe/guestinfo_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/M, cla-not-required

#666 ✨ Emit distinct create/update VM events
  .golangci.yml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  pkg/context/operation/operation_context.go
  pkg/context/operation/operation_context_test.go
  pkg/context/operation/operation_suite_test.go
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/vsphere/vm/power_state.go
  test/builder/unit_test_context.go
Labels: size/XL, cla-not-required

#667 🌱 Update envtest k8s version to 1.29.1
  controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
  hack/tools/Makefile
Labels: size/XS, cla-not-required

#662 ✨ Implement Backup-version for Incremental Restore support
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  test/builder/vcsim_test_context.go
Labels: size/XXL, cla-not-required

#668 🌱 Avoid duplicate VM ReconcileNormal events
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
Labels: size/M, cla-not-required

#671 🐛 Stop adding ":detaching" to volumes more than once
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
Labels: size/S, cla-not-required

#675 🌱 Controller-runtime v0.19.0 & Controller-tools v0.16.1
  .golangci.yml
  api/go.mod
  api/go.sum
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_contentlibraryproviders.yaml
  config/crd/bases/vmoperator.vmware.com_contentsourcebindings.yaml
  config/crd/bases/vmoperator.vmware.com_contentsources.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclassbindings.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml
  config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
  config/crd/external-crds/cns.vmware.com_storagepolicyquotas.yaml
  config/crd/external-crds/cns.vmware.com_storagepolicyusages.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraryitems.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitemimportrequests.yaml
  config/crd/external-crds/imageregistry.vmware.com_contentlibraryitems.yaml
  config/crd/external-crds/netoperator.vmware.com_networkinterfaces.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_availabilityzones.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_vspherezones.yaml
  config/crd/external-crds/topology.tanzu.vmware.com_zones.yaml
  config/rbac/role.yaml
  controllers/contentlibrary/utils/test_utils.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/prober/fake/worker/fake_prober_worker.go
  pkg/prober/prober_manager.go
  pkg/prober/worker/prober_worker.go
  pkg/prober/worker/readiness_worker.go
  test/builder/dummies.go
Labels: size/XL, cla-not-required

#672 🌱 Define FSS for Bring your own (encryption) key (BYOK)
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/M, cla-not-required

#670 ✨ Introduce EncryptionClass API
  .golangci.yml
  Makefile
  config/crd/external-crds/vmencryption.vmware.com_encryptionclasses.yaml
  config/default/kustomization.yaml
  external/byok/api/v1alpha1/doc.go
  external/byok/api/v1alpha1/encryptionclass_types.go
  external/byok/api/v1alpha1/groupversion_info.go
  external/byok/api/v1alpha1/zz_generated.deepcopy.go
  external/byok/go.mod
  external/byok/go.sum
  go.mod
  pkg/manager/manager.go
  test/builder/fake.go
Labels: size/L, cla-not-required

#676 🌱 Use string.Builder for backup yaml doc
  pkg/providers/vsphere/virtualmachine/backup.go
Labels: size/S, cla-not-required

#677 🌱 Use PartialObjectMetadata to unmarshal VM for backup needed check
  pkg/providers/vsphere/virtualmachine/backup.go
Labels: size/S, cla-not-required

#674 ✨ Back up classic disk data in VM ExtraConfig
  .golangci.yml
  api/backup/backup.go
  api/backup/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/L, cla-not-required

#663 🌱 Handle zones that are being deleted under WCP_Workload_Domain_Isolation
  pkg/providers/vsphere/placement/zone_placement.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/topology/availability_zones_test.go
  test/builder/dummies.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#636 :seedling: Rename the pause-reconcile annotation to paused
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_types.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/util/annotations/helpers.go
  pkg/util/annotations/helpers_suite_test.go
  pkg/util/annotations/helpers_test.go
Labels: size/L, cla-not-required

#680 ✨ Introduce ExtraConfig key for enable automatic registration
  api/backup/backup.go
Labels: size/S, cla-not-required

#682 🐛 Fix panic when logging ConfigSpec w nil iface pointer
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig_test.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
Labels: size/M, cla-not-required

#679 🌱 Use controller-runtime built-in pprof server
  main.go
  pkg/manager/manager.go
  pkg/manager/options.go
Labels: size/M, cla-not-required

#678 🐛 Start infra capability controller for non-leader pods too
  controllers/infra/capability/infra_capability_controller.go
  controllers/infra/capability/infra_capability_controller_suite_test.go
  controllers/infra/capability/infra_capability_controller_unit_test.go
  pkg/manager/cache.go
Labels: size/M, cla-not-required

#686 🌱 Remove the gnotify workflow
  .github/workflows/gnotify.py
  .github/workflows/gnotify.requirements
  .github/workflows/gnotify.yml
Labels: size/L, cla-not-required

#683 :seedling: Update VPC APIs to latest version
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  test/builder/fake.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
Labels: size/S, cla-not-required

#688 🐛 Handle disk backing changes when backing up PVCDiskData
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/M, cla-not-required

#685 🌱 Introduce condition to indicate the status of latest backup
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/L, cla-not-required

#687 Use ResourcePool field out of the VM properties
  pkg/providers/vsphere/session/session.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/L, cla-not-required

#669 📖 Add initial VM resize docs
  docs/concepts/workloads/vm.md
  docs/start/quick.md
Labels: size/S, cla-not-required
