Repository vmware-tanzu/vm-operator, pull requests merged in 2024-07, with the labels that each got.

#605 🌱 Reduce Volume controller log spam while creating VMs
  controllers/volume/volume_controller.go
Labels: size/XS

#604 ✨ Initial resize when powering on VM support
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
Labels: size/M

#609 🌱 Placeholder FSS for Unified Storage Quota
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#607 🌱 Update StoragePolicyQuota v1a1 APIs
  .gitignore
  Makefile
  external/storage-policy-quota/api/v1alpha1/doc.go
  external/storage-policy-quota/api/v1alpha1/groupversion_info.go
  external/storage-policy-quota/api/v1alpha1/storagepolicyquota_types.go
  external/storage-policy-quota/api/v1alpha1/storagepolicyusage_types.go
  external/storage-policy-quota/api/v1alpha1/storagequota_types.go
  external/storage-policy-quota/api/v1alpha1/zz_generated.deepcopy.go
  external/storage-policy-quota/go.mod
  external/storage-policy-quota/go.sum
  external/vsphere-csi-driver/pkg/syncer/cnsoperator/apis/storagepolicy/v1alpha1/zz_generated.deepcopy.go
  go.mod
  pkg/manager/manager.go
  test/builder/dummies.go
  test/builder/fake.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#608 🌱 Move device related resize into separate files
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_devices.go
  pkg/util/resize/configspec_devices_test.go
  pkg/util/resize/configspec_test.go
Labels: size/XL, cla-not-required

#603 ✨Resize N_Port ID Virtualization settings
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L

#579 🌱 Add the vCenter UUID annotation on the VM
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/S, cla-not-required

#611 🌱 Go 1.22.5
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  go.mod
  hack/tools/go.mod
Labels: size/S, cla-not-required

#612 ✨Resize SGX (Software Guard Extension) for VMs
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#613 🌱 Remove resize console preferences
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#614 🐛 Ignore VM Class specified default guestID "otherGuest64"
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
Labels: size/XS, cla-not-required

#615 ✨ Resize vPMem and VM Tools config
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#616 🌱 Add image type in VirtualMachineImage and ClusterVirtualMachineImage status
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachineimage_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachineimage_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
  docs/ref/api/v1alpha3.md
Labels: size/S, cla-not-required

#610 ✨ Resize Virtual Numa nodes
  go.mod
  go.sum
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#620 :bug: Revert to returning early if the pause annotation is present on the VM
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_unit_test.go
Labels: size/S, cla-not-required

#622 🐛 Set VirtualDisk.UnitNumber when placing with multiple clusters
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/XS, cla-not-required

#619 ✨ Storage usage in VirtualMachine API status
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_storage_types.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/volume/volume_controller.go
  controllers/volume/volume_controller_unit_test.go
  go.mod
  go.sum
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/XXL, cla-not-required

#621 ✨ Update VM mutating/validating webhook related to CD-ROM spec
  test/builder/dummies.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#617 :seedling: Plumb FSS for Workload Domain Isolation and vendor Zone APIs
  config/crd/external-crds/topology.tanzu.vmware.com_zones.yaml
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  external/tanzu-topology/api/v1alpha1/zone.go
  external/tanzu-topology/api/v1alpha1/zz_generated.deepcopy.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/L, cla-not-required

#625 Revert "Storage Policy Quota v1alpha2 APIs"
  external/storage-policy-quota/api/v1alpha1/doc.go
  external/storage-policy-quota/api/v1alpha1/groupversion_info.go
  external/storage-policy-quota/api/v1alpha2/doc.go
  external/storage-policy-quota/api/v1alpha2/groupversion_info.go
  external/storage-policy-quota/api/v1alpha2/storagepolicyquota_types.go
  external/storage-policy-quota/api/v1alpha2/storagepolicyusage_types.go
  external/storage-policy-quota/api/v1alpha2/storagequota_types.go
  external/storage-policy-quota/api/v1alpha2/zz_generated.deepcopy.go
  pkg/manager/manager.go
  test/builder/dummies.go
  test/builder/fake.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#628 🌱 resize: support same class annotation on brownfield VMs
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/vmopv1/resize.go
  pkg/util/vmopv1/resize_test.go
Labels: size/M, cla-not-required

#626 🌱 StoragePolicyQuota controller
  .gitignore
  config/crd/external-crds/cns.vmware.com_storagepolicyquotas.yaml
  config/crd/external-crds/cns.vmware.com_storagepolicyusages.yaml
  config/rbac/role.yaml
  controllers/controllers.go
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
  controllers/storagepolicyquota/storagepolicyusage_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyusage_controller_unit_test.go
  pkg/util/kube/gvk.go
  pkg/util/kube/spq.go
  pkg/util/kube/spq_test.go
Labels: size/XL, cla-not-required

#629 🌱 resize: update VM Status.Class after resizing
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
Labels: size/M, cla-not-required

#631 :seedling: Introduce the ExtraConfig key to allow opt-out from auto register
  api/v1alpha3/virtualmachine_types.go
Labels: size/S, cla-not-required

#634 🐛 Only set vmPathName when using ISO image
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/S, cla-not-required

#630 🌱 Add FSS_WCP_VMSERVICE_RESIZE_CPU_MEMORY
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#624 :seedling: Include both vm_name and interface_name in VPCAttachmentRef
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
Labels: size/XS, cla-not-required

#627 ✨ resize: Start to handle more device types
  pkg/util/resize/backings.go
  pkg/util/resize/backings_test.go
  pkg/util/resize/configspec_devices.go
  pkg/util/resize/configspec_devices_test.go
Labels: size/XXL, cla-not-required

#633 ✨ resize: VM resize of just CPU and Memory
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#640 🌱 Skip default LinuxPrep bootstrap for ISO VM deployment
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
Labels: size/XS, cla-not-required

#637 :seedling: Introduce an annotation for unconditional opt into backup
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/annotations/helpers.go
  pkg/util/annotations/helpers_test.go
Labels: size/M, cla-not-required

#638 :sparkles: Update zone placement under WCP_Workload_Domain_Isolation
  Makefile
  config/crd/external-crds/topology.tanzu.vmware.com_zones.yaml
  config/rbac/role.yaml
  external/tanzu-topology/api/v1alpha1/zone.go
  external/tanzu-topology/api/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/vsphere/placement/zone_placement.go
  pkg/topology/availability_zones.go
  pkg/topology/availability_zones_test.go
  test/builder/dummies.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#639 🌱 resize: add condition to indicate if resize is available
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required
