Repository vmware-tanzu/vm-operator, pull requests merged in 2024-09, with the labels that each got.

#691 🌱 Refactor VM Op imports out of util/vsphere/vm
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/virtualmachine/cdrom.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/virtualmachine/extraconfig.go
  pkg/providers/vsphere/virtualmachine/extraconfig_test.go
  pkg/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
  pkg/util/vsphere/vm/vm.go
  pkg/util/vsphere/vm/vm_suite_test.go
  pkg/util/vsphere/vm/vm_test.go
Labels: size/L, cla-not-required

#692 🌱 Support podman
  Makefile
  hack/build-container.sh
Labels: size/M, cla-not-required

#693 :bug: Do not reconcile volumes if VM has pause annotation set
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_intg_test.go
Labels: size/M, cla-not-required

#694 :seedling: Update VPC APIs to latest v4.0.2
  go.mod
  go.sum
Labels: size/XS, cla-not-required

#699 🌱 Change Backup version to use UnixMilli()
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/XS, cla-not-required

#700 Allow imageless VM creation when Incremental Restore FSS is enabled
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#698 🌱 Drop managedFields and last-applied-config annotation from backup
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/L, cla-not-required

#696 📖 Remove stale VirtualMachineVolumeStatus comment
  api/v1alpha3/virtualmachine_storage_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/XS, cla-not-required

#702 🌱 Update guest ID and cdrom.connected API docs
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
Labels: size/S, cla-not-required

#690 ✨ Use capabilities at start up time
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/infra/capability/infra_capability_controller.go
  controllers/infra/capability/infra_capability_controller_intg_test.go
  controllers/infra/capability/infra_capability_controller_unit_test.go
  main.go
  pkg/config/capabilities/capabilities_suite_test.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env/env_suite_test.go
  pkg/config/env_test.go
  pkg/manager/init/init_providers.go
Labels: size/L, cla-not-required

#703 🌱 Go 1.22.7
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  go.mod
  hack/tools/go.mod
Labels: size/S, cla-not-required

#704 🐛 Use cached Get() of PVCs in Volume controller
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
Labels: size/S, cla-not-required

#705 Revert "Go 1.22.7" back to "Go 1.22.5"
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  go.mod
  hack/tools/go.mod
Labels: size/S, cla-not-required

#706 Re-introduce Go 1.22.7
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  go.mod
  hack/tools/go.mod
Labels: size/S, cla-not-required

#707 ✨ Strip managed fields for cached objects
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  pkg/manager/cache.go
  pkg/manager/manager.go
  pkg/providers/vsphere/network/network.go
Labels: size/M, cla-not-required

#708 🐛 Match VMs if class name is empty in predicate
  pkg/util/kube/predicates.go
Labels: size/XS, cla-not-required

#689 🐛 Have EnsureDisksHaveControllers() alloc unit numbers
  go.mod
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/util/ensure_disk_controller.go
  pkg/util/ensure_disk_controller_test.go
Labels: size/XL, cla-not-required

#712 :seedling: Rebrand NSX-T to NSX
  pkg/providers/vsphere/network/nsxt.go
Labels: size/S, cla-not-required

#711 🌱 Allow CAPV to still create VMs in draining zones
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M, cla-not-required

#715 :seedling: Temporarily disable markdown & shell lint jobs
  .github/workflows/ci.yml
Labels: size/M, cla-not-required

#716 🌱 Add FSS_WCP_SIMPLIFIED_ENABLEMENT
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#718 🐛 Fix NPE when converting partial inline sysprep
  api/v1alpha2/sysprep/conversion/v1alpha2/sysprep_conversion.go
  api/v1alpha2/sysprep/conversion/v1alpha3/sysprep_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
Labels: size/M, cla-not-required

#710 🐛 Don't fail if nameservers are empty in network CM
  pkg/providers/vsphere/config/config.go
  pkg/providers/vsphere/config/config_test.go
Labels: size/M, cla-not-required

#717 🐛 Only CPU/Memory resize when actually needed
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/XL, cla-not-required

#720 :seedling: Update StoragePolicyQuota to consume v1alpha2
  config/crd/external-crds/cns.vmware.com_storagepolicyquotas.yaml
  config/crd/external-crds/cns.vmware.com_storagepolicyusages.yaml
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  external/storage-policy-quota/api/v1alpha2/groupversion_info.go
  external/storage-policy-quota/api/v1alpha2/storagepolicyquota_types.go
  external/storage-policy-quota/api/v1alpha2/storagepolicyusage_types.go
  external/storage-policy-quota/api/v1alpha2/storagequota_types.go
  external/storage-policy-quota/api/v1alpha2/zz_generated.deepcopy.go
  pkg/manager/manager.go
  pkg/util/kube/spq/spq.go
  pkg/util/kube/spq/spq_test.go
  test/builder/dummies.go
  test/builder/fake.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/XL, cla-not-required

#719 ✨Support for reserved VM Classes
  api/v1alpha1/virtualmachineclass_conversion.go
  api/v1alpha1/virtualmachineclass_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachineclass_conversion.go
  api/v1alpha2/virtualmachineclass_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachineclass_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
  pkg/providers/vsphere/constants/constants.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/L, cla-not-required

#723 🌱 Restrict VM Class reserved slots >=0
  api/v1alpha1/virtualmachineclass_conversion.go
  api/v1alpha1/virtualmachineclass_conversion_test.go
  api/v1alpha2/virtualmachineclass_conversion.go
  api/v1alpha2/virtualmachineclass_conversion_test.go
  api/v1alpha3/virtualmachineclass_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
Labels: size/L, cla-not-required

#724 :seedling: Do not fall back to using filenames for PVC disk backup
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/M, cla-not-required
