Repository vmware-tanzu/vm-operator, pull requests merged in 2024-06, with the labels that each got.

#551 🌱 Increase coverage for VM Class controller to >70%
  controllers/virtualmachineclass/virtualmachineclass_controller_unit_test.go
Labels: size/M, cla-not-required

#550 🌱 Misc topology cleanup
  pkg/topology/availability_zones.go
  pkg/topology/availability_zones_test.go
Labels: size/M, cla-not-required

#556 🐛 Fix coverage for both patch packages
  controllers/virtualmachinewebconsolerequest/v1alpha1/patch/suite_test.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/patch/utils_test.go
  pkg/patch/suite_test.go
  pkg/patch/utils_test.go
Labels: size/XL, cla-not-required

#555 🌱 Increase coverage for pkg/builder >95%
  pkg/builder/builder_suite_test.go
  pkg/builder/mutating_webhook.go
  pkg/builder/mutating_webhook_test.go
  pkg/builder/validating_webhook_test.go
Labels: size/XL, cla-not-required

#558 🐛 Additional fixes for YAML->JSON tags
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
Labels: size/M, cla-not-required

#560 🌱 Increase coverage for session pkg from 33-->76%
  pkg/providers/vsphere/session/session.go
  pkg/providers/vsphere/session/session_suite_test.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  test/builder/vcsim_test_context.go
Labels: size/XL, cla-not-required

#561 🌱 Increase coverage for prober from 55-->91%
  pkg/prober/prober_manager_test.go
Labels: size/M, cla-not-required

#562 🌱 Coverage thresholds; fail on below 80%
  .github/workflows/ci.yml
Labels: size/XS, cla-not-required

#564 🌱 Upgrade go1.22.4 to address vulnerability GO-2024-2887
  .github/workflows/ci.yml
  Dockerfile
  api/go.mod
  go.mod
  hack/tools/go.mod
Labels: size/S, cla-not-required

#565 🌱 Default GOTOOLCHAIN to LOCAL
  Makefile
Labels: size/XS, cla-not-required

#559 ✨ Resize fields: CPU affinity, hot add, hot remove, latency sensitivity, perf counter, resource allocation
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#557 ✨ Handle VM Class Resize annotations
  api/v1alpha3/virtualmachine_types.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/ptr/ptr.go
  pkg/util/ptr/ptr_test.go
  pkg/util/resize/configspec.go
  pkg/util/vmopv1/resize.go
  pkg/util/vmopv1/resize_devops.go
  pkg/util/vmopv1/resize_devops_test.go
  pkg/util/vmopv1/resize_test.go
Labels: size/XL, cla-not-required

#566 🌱 Handle resize of vGPU and DDPIO devices
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#567 ✨ Resize ExtraConfig
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/S, cla-not-required

#568 🐛 Fix VM controller VM Class reconcile request handler
  controllers/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine_controller_intg_test.go
Labels: size/L, cla-not-required

#569 🌱 Update testing -- resize ExtraConfig
  pkg/util/resize/configspec_test.go
Labels: size/S, cla-not-required

#572 🌱 Increase coverage for web-console-validation server from 51-->100%
  cmd/web-console-validator/main.go
  pkg/webconsolevalidation/server.go
  pkg/webconsolevalidation/server_test.go
Labels: size/L, cla-not-required

#575 🌱 Remove unused VM Image related annotation consts
  pkg/providers/vsphere/constants/constants.go
Labels: size/XS, cla-not-required

#573 🌱 Resize Annotation and ManagedBy fields
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#578 🌱 Skip syncing VMI content for non-OVF type content library items
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
  test/builder/vcsim_test_context.go
Labels: size/L, cla-not-required

#580 :book: Sync VirtualMachineReplicaSet API docs generated from CRDs
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
Labels: cla-not-required

#577 🐛 EnsureAllDisksPointToController
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/ensure_disk_controller.go
  pkg/util/ensure_disk_controller_test.go
Labels: size/XXL, cla-not-required

#576 ✨ Resize Console Preferences
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#563 ✨ Add vm.spec.guestID API and its implementation
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha3.md
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/util/vmopv1/network.go
  pkg/util/vmopv1/network_test.go
  pkg/util/vsphere/vm/guest_id.go
  pkg/util/vsphere/vm/guest_id_test.go
  pkg/util/vsphere/vm/suite_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#582 ✨Resize Flags: CBRC Cache Enabled
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#584 🌱 Add NCP protocol annotation if NCP port health check
  controllers/virtualmachineservice/providers/loadbalancer_provider.go
  controllers/virtualmachineservice/providers/loadbalancer_provider_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
Labels: size/S, cla-not-required

#586 🐛 Fix v1a1 CloudInit with no user-data only ssh public keys
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
Labels: size/S, cla-not-required

#583 🌱 Resize Brownfield VMs
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L, cla-not-required

#571 🌱 OptionValues helper
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/option_values.go
  pkg/util/option_values_test.go
  pkg/util/resize/configspec.go
Labels: size/XXL, cla-not-required

#589 ✨ Resize FlagInfo
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#590 ✨ Resize Memory Allocation and Memory Hot Add
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/L, cla-not-required

#595 🐛 Revert "Merge pull request #584 from akutz/feature/vmsvc-ncp-health-check"
  controllers/virtualmachineservice/providers/loadbalancer_provider.go
  controllers/virtualmachineservice/providers/loadbalancer_provider_test.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
Labels: size/S, cla-not-required

#591 🌱 Support MMIO ExtraConfig during resize
  pkg/util/option_values.go
  pkg/util/option_values_test.go
  pkg/util/vmopv1/resize_devops.go
  pkg/util/vmopv1/resize_devops_test.go
Labels: size/L, cla-not-required

#587 🌱 Create a new Capability controller to watch the wcp-cluster-capabilities ConfigMap
  controllers/infra/capability/infra_capability_controller.go
  controllers/infra/capability/infra_capability_controller_intg_test.go
  controllers/infra/capability/infra_capability_controller_suite_test.go
  controllers/infra/capability/infra_capability_controller_unit_test.go
  controllers/infra/controllers.go
Labels: size/L, cla-not-required

#593 ✨ Resize Miscellaneous bool configSpec fields
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#602 🌱 Move comment about default network to right spot
  pkg/providers/vsphere/network/network.go
Labels: size/XS, cla-not-required

#592 ✨Resize: Memory Reservation Locked to Max
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#597 ✨ Resize: Guest Monitoring (GMM) and Encrypted vMotion modes
  pkg/util/resize/configspec.go
  pkg/util/resize/configspec_test.go
Labels: size/M, cla-not-required

#596 🌱 Handle more ExtraConfig fields during resize
  pkg/util/configspec.go
  pkg/util/configspec_test.go
  pkg/util/vmopv1/resize_devops_test.go
  pkg/util/vmopv1/resize_overwrite.go
  pkg/util/vmopv1/resize_overwrite_test.go
Labels: size/L, cla-not-required

#600 🌱 Resize: VM.Spec.GuestID support
  pkg/util/vmopv1/resize_overwrite.go
  pkg/util/vmopv1/resize_overwrite_test.go
Labels: size/M, cla-not-required

#601 🌱 Remove duplicate VM.Status.Class assignment
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
Labels: size/S, cla-not-required

#606 🌱 Don't backfill VM Status.Class in classless VMs
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
Labels: size/M
