Repository vmware-tanzu/vm-operator, pull requests merged in 2025-10, with the labels that each got.

#1213 🐛 Fix setting Sysprep password without AutoLogin
  pkg/providers/vsphere/sysprep/secret.go
  pkg/providers/vsphere/sysprep/secret_test.go
Labels: size/M

#1018 🐛 x-port 8.0.3: Fix PCI DVX devs on update
  pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
  pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
Labels: size/L

#1217 🌱 Cleanup duplicate Sysprep secret fetching
  pkg/providers/vsphere/sysprep/secret.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/util/sysprep/secret.go
  pkg/util/sysprep/secret_test.go
  pkg/util/sysprep/suite_test.go
Labels: size/L

#1221 🌱 Disallow LinuxPrep password when VCD parity is not enabled
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M

#1219 ⚠️ Update VirtualMachine Affinity/Anti-Affinity APIs
  api/test/v1alpha1/virtualmachine_conversion_test.go
  api/test/v1alpha2/virtualmachine_conversion_test.go
  api/test/v1alpha3/virtualmachine_conversion_test.go
  api/test/v1alpha4/virtualmachine_conversion_test.go
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_affinity_types.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/virtualmachine_affinity_types.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/virtualmachine_affinity_types.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1alpha5/virtualmachine_affinity_types.go
  api/v1alpha5/virtualmachine_types.go
  api/v1alpha5/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/providers/vsphere/vmprovider_vm_group_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XXL

#1202 🌱Implement greenfield volume attach of WFFC type volumes
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_intg_test.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  controllers/virtualmachine/volumebatch/volumebatch_controller.go
  controllers/virtualmachine/volumebatch/volumebatch_controller_suite_test.go
  controllers/virtualmachine/volumebatch/volumebatch_controller_unit_test.go
  controllers/virtualmachineservice/utils/constants.go
  go.mod
  go.sum
  pkg/providers/vsphere/constants/constants.go
  pkg/util/cns.go
  pkg/util/cns_test.go
Labels: size/XXL

#1214 🌱 Skip VM with zone label and address recreated VM in group placement
  api/v1alpha2/virtualmachinegroup_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachinegroup_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachinegroup_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/virtualmachinegroup_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
  pkg/providers/vsphere/vmprovider_vm_group.go
  pkg/providers/vsphere/vmprovider_vm_group_test.go
Labels: size/L

#1222 🌱 Add capability for VSphere policies
  pkg/config/capabilities/capabilities.go
  pkg/config/capabilities/capabilities_test.go
Labels: size/M

#1224 Add a log statement that prints UserInfo object
  pkg/builder/auth.go
Labels: size/XS

#1184 📖 Add docs around VM placement
  docs/concepts/workloads/vm-placement.md
  docs/concepts/workloads/vm.md
  mkdocs.yml
Labels: size/L

#1198 🌱Report VM's snapshot usage separately in VM Spec
  api/test/v1alpha4/virtualmachine_conversion_test.go
  api/v1alpha4/virtualmachine_conversion.go
  api/v1alpha4/virtualmachine_storage_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/virtualmachine_storage_types.go
  api/v1alpha5/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/virtualmachine/snapshot.go
  pkg/providers/vsphere/virtualmachine/snapshot_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
Labels: size/XXL
