Repository vmware-tanzu/vm-operator, pull requests merged in 2025-04, with the labels that each got.

#924 🌱 Create StoragePolicyQuota in vcsim test env
  test/builder/vcsim_test_context.go
Labels: size/M, cla-not-required

#910 🌱 Various VM validation webhook clean up
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#923 🐛 Always set ConfigSpec CpuAllocation.Shares field
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/M, cla-not-required

#925 🐛 Fix StorageClass usage for VMs
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
Labels: size/M, cla-not-required

#927 🐛 Defer content version check when Fast Deploy
  controllers/contentlibrary/utils/controller_builder.go
Labels: size/S, cla-not-required

#926 [x-port 9.0] 🐛 Fix StorageClass usage for VMs
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
Labels: size/M, cla-not-required

#934 🌱 Golang 1.24.2
  go.mod
  hack/tools/go.mod
Labels: size/XS

#928 :seedling: Remove duplicate property fetch during backup
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/M, cla-not-required

#931 🐛 Set device key for passthrough devices for placement
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/S, cla-not-required

#935 🌱 Allow changes to VM Spec.Networks.Interfaces
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#936 🐛 Require VM ResourcePolicyName when specifying a cluster module
  pkg/constants/constants.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/vmoperator.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#938 🌱 Set VM as controller owner ref on network interfaces
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
Labels: size/L

#941 🌱 Remove enabled FSS STORAGE_QUOTA_M2 from vmoperator code
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/controllers.go
  controllers/infra/controllers.go
  controllers/virtualmachine/controllers.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  webhooks/webhooks.go
Labels: size/M

#940 📖 Fix swapped key and name field in cloud init example
  docs/concepts/workloads/guest.md
Labels: size/XS

#943 FastDeploy: Use Datastore method to check if cache files exist
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
  pkg/util/vsphere/library/item_cache.go
  pkg/util/vsphere/library/item_cache_test.go
Labels: size/L

#946 ✨ Support poweron.check and delete.check annotations
  api/v1alpha4/virtualmachine_types.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  docs/concepts/workloads/vm.md
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL
