Repository vmware-tanzu/vm-operator, pull requests merged in 2025-01, with the labels that each got.

#846 🐛 Decrement concurrent creates if getCreateArgs fails
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/S, cla-not-required

#853 🐛 Fix empty VMI Status.Disks[] after upgrade
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
Labels: size/XS, cla-not-required

#850 :seedling: Remove FSS_WCP_TKG_Multiple_CL
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
Labels: size/S, cla-not-required

#857 📖 Update VM crypto docs on rekey
  docs/concepts/workloads/vm.md
Labels: size/M, cla-not-required

#856 🐛 Background reconcile awareness support
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L, cla-not-required

#855 🌱 Consistently use the default config for controller integration tests
  controllers/infra/capability/configmap/configmap_capability_controller_suite_test.go
  controllers/infra/capability/configmap/configmap_capability_controller_test.go
  controllers/infra/capability/crd/crd_capability_controller_suite_test.go
  controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_suite_test.go
  controllers/storageclass/storageclass_controller_suite_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_suite_test.go
  test/builder/test_suite.go
Labels: size/S, cla-not-required

#859 🌱 Raise log level of VM Class to VM request mapper func
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
Labels: size/XS, cla-not-required

#860 🌱 Remove FSS WorkloadDomainIsolation
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/infra/zone/zone_controller_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller.go
  controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_suite_test.go
  main.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/vcenter/folder_test.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vcenter/resourcepool_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_resourcepolicy_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  services/vm-watcher/vm_watcher_service_test.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required

#862 🌱 Emit memory statistics to log file / prometheus
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  main.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/mem/mem.go
  pkg/mem/mem_suite_test.go
  pkg/mem/mem_test.go
Labels: size/L, cla-not-required

#863 🌱 Invert flags for AsyncSignal & Create
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
  pkg/util/vsphere/watcher/watcher_context.go
  pkg/util/vsphere/watcher/watcher_context_test.go
  pkg/util/vsphere/watcher/watcher_test.go
  services/services.go
Labels: size/L, cla-not-required

#865 🐛 Update storage status
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha3/virtualmachine_storage_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
Labels: size/L, cla-not-required

#866 🐛 Handle invalid VC Session in GetVirtualMachine()
  pkg/providers/vsphere/vcenter/getvm.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vmprovider.go
Labels: size/L, cla-not-required

#868 🐛 Do not panic in CLS controllers
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
  controllers/contentlibrary/utils/controller_builder.go
  controllers/contentlibrary/utils/controller_builder_test.go
Labels: size/M, cla-not-required

#867 🌱 Use consistent import alias for govmomi/pbm/types
  .golangci.yml
  pkg/providers/vsphere/storage/provisioning.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/S, cla-not-required

#861 🌱 Update cluster modules provider to use context logger
  pkg/providers/vsphere/clustermodules/cluster_modules.go
  pkg/providers/vsphere/clustermodules/cluster_modules_provider.go
  pkg/providers/vsphere/clustermodules/cluster_modules_test.go
  test/builder/vcsim_test_context.go
Labels: size/M, cla-not-required

#869 :seedling: Increase CPU and memory limits for the controller manager pod
  config/wcp/vmoperator/cpu_resources_patch.yaml
Labels: size/XS, cla-not-required

#871 🌱 Go 1.23.5 / GH Action uses go.mod
  .github/workflows/ci.yml
  go.mod
Labels: size/S

#864 :seedling: Include UUID of disk backing in disk backup
  pkg/backup/api/backup_types.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/S, cla-not-required

#873 Fix missing labels on CVMI resources
  controllers/contentlibrary/utils/controller_builder.go
  controllers/contentlibrary/utils/controller_builder_test.go
Labels: size/L

#875 🐛 Fix duplicate append of Image.Status fields
  controllers/contentlibrary/utils/controller_builder.go
  controllers/contentlibrary/utils/controller_builder_test.go
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/contentlibrary/content_library_utils_test.go
Labels: size/M
