Repository vmware-tanzu/vm-operator, pull requests merged in 2025-08, with the labels that each got.

#1063 ✨ Support for VM-backed images
  api/v1alpha3/virtualmachineimagecache_types.go
  api/v1alpha4/virtualmachineimage_types.go
  api/v1alpha4/virtualmachineimagecache_types.go
  config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimagecaches.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmlifecycle/create_fastdeploy.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/kube/resources.go
  pkg/util/kube/resources_test.go
  pkg/util/vmopv1/image.go
  pkg/util/vmopv1/image_test.go
  pkg/util/vsphere/library/item_cache.go
  pkg/util/vsphere/library/item_cache_test.go
Labels: size/XXL

#1072 🐛 Fix use of old condition constant
  pkg/providers/vsphere/vmprovider_vm_group_test.go
Labels: size/XS

#1079 🌱 Restore prior placement request/response log levels
  pkg/providers/vsphere/placement/cluster_placement.go
Labels: size/XS

#1073 ✨ update the CM's membership when the VM is in the steady-state
  pkg/constants/constants.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/dummies.go
Labels: size/L

#1067 ✨Report reserved and used capacity of VMSnapshot in its StoragePolicyUsage
  api/v1alpha4/virtualmachinesnapshot_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinesnapshots.yaml
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_suite_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_intg_test.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_suite_test.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_unit_test.go
  pkg/constants/constants.go
  pkg/context/virtualmachinesnapshot_context.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/virtualmachine/snapshot.go
  pkg/providers/vsphere/virtualmachine/snapshot_test.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/util/kube/spq/spq.go
  pkg/util/kube/vmsnapshot.go
  pkg/util/kube/vmsnapshot_test.go
  test/builder/dummies.go
  webhooks/virtualmachinereplicaset/validation/virtualmachinereplicaset_validator_unit_test.go
Labels: size/XXL

#1089 🌱 (xport 9.0.1) perform client cert verification for admission webhooks (#1076)
  config/default/manager_webhook_patch.yaml
  config/wcp/vmoperator/kustomization.yaml
  config/wcp/vmoperator/manager_webhook_client_ca_patch.yaml
  main.go
  pkg/builder/auth.go
  pkg/builder/auth_test.go
  pkg/builder/builder_suite_test.go
  pkg/builder/mutating_webhook.go
  pkg/builder/mutating_webhook_test.go
  pkg/builder/validating_webhook.go
  pkg/builder/validating_webhook_test.go
  pkg/context/controller_manager_context.go
  pkg/context/webhook_context.go
  pkg/manager/manager.go
  pkg/manager/options.go
Labels: size/L

#1086 🌱 Only create SPU for snapshot when its feature gate is enabled
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
Labels: size/L

#1087 🌱Sync ginkgo version in hack/tools
  api/go.mod
  api/go.sum
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/S

#1090 🌱(xport 9.0.1) Only create SPU for snapshot when its feature gate is enabled (#1086)
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
Labels: size/L

#1085 🐛 Log the VM's recent tasks on reconcile / ignore certain tasks
  pkg/context/virtualmachine_context.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
Labels: size/M

#1083 🌱 Exclude snapshot related disks/files when calculating VM status storage usage
  api/v1alpha4/virtualmachine_storage_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  go.mod
  go.sum
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
Labels: size/L

#1101 X-Port 9.0.1 -- 🐛 Disable ExternalID for NetOP interfaces
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
Labels: size/XS

#1094 🌱 Add back Ethernet cards to placement ConfigSpec
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/M

#1097 :seedling: Prevent snapshot of VKS nodes
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go
Labels: size/L

#1099 🌱 Enqueue reconcile between groups and linked members
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
Labels: size/L

#1112 🌱 sort the content library names if multiple default ones are found
  webhooks/common/utils.go
Labels: size/XS

#1114 🌱 Prevent duplicate and self referenced members in VM Group
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_intg_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go
Labels: size/L

#1106 ✨ Add support for publishing a VM to non-CLS backed libraries
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/virtualmachine/publish.go
  pkg/providers/vsphere/virtualmachine/publish_test.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_vm.go
  test/builder/dummies.go
Labels: size/L

#1128 :seedling: Enable v1a2 (cluster)contentlibraryitem controller(s)
  controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
  controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
Labels: size/S

#1131 :seedling: Allow v1alpha2 spec.target.location.apiVersion in VirtualMachinePublishRequest validating webhook
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator.go
  webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_unit_test.go
Labels: size/XS

#1132 🐛Register conversion function to pointer of scheme
  api/test/v1alpha1/conversion_test.go
  api/test/v1alpha2/conversion_test.go
  api/test/v1alpha3/conversion_test.go
  api/test/v1alpha4/conversion_test.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha3/groupversion_info.go
  api/v1alpha4/groupversion_info.go
  external/byok/api/v1alpha1/groupversion_info.go
  external/capabilities/api/v1alpha1/groupversion_info.go
Labels: size/M

#1134 🐛Only reconcile SPU for Snapshot when feature is enabled
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
Labels: size/XL

#1126 🌱 Set group linked condition for nested child groups
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachinegroup_types.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/virtualmachinegroup_types.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinegroup_types.go
  api/v1alpha5/virtualmachine_types.go
  api/v1alpha5/virtualmachinegroup_types.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/vmopv1/vmgroup.go
  pkg/util/vmopv1/vmgroup_test.go
Labels: size/XL

#1118 🌱 Tweak StoragePolicyUsage controller allocs
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
Labels: size/M

#1136 :bug: Update SyncVirtualMachineImage check to account for v1alpha2 ContentLibraryItem and ClusterContentLibraryItem types
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
Labels: size/S

#1138 :seedling: Support MatchExpressions when specifying VM-VM zonal affinity
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/L
