Repository vmware-tanzu/vm-operator, pull requests merged in 2025-07, with the labels that each got.

#1028 :seedling: Introduce a capability for VM Snapshots
  controllers/controllers.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
Labels: size/M

#1034 🌱 Handle network interface changes when VM is in powered off state
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
Labels: size/L

#1040 🌱 Add virtualmachinesnapshot validation webhook
  config/webhook/manifests.yaml
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_intg_test.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_suite_test.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go
  webhooks/virtualmachinesnapshot/webhooks.go
  webhooks/webhooks.go
Labels: size/L

#1041 :sparkles: Add support for reverting a VM to a given snapshot
  pkg/constants/constants.go
  pkg/providers/vsphere/virtualmachine/snapshot.go
  pkg/providers/vsphere/virtualmachine/snapshot_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/vcsim_test_context.go
Labels: size/XXL

#1043 🌱 Update vm.status.currentSnapshot in snapshot controller
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_intg_test.go
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_unit_test.go
  pkg/providers/vsphere/virtualmachine/snapshot.go
Labels: size/L

#1046 🌱Create StoragePolicyQuota for VMSnapshot
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  pkg/util/kube/spq/spq.go
  pkg/util/kube/spq/spq_test.go
Labels: size/L

#1048 :seedling: Remove references to VM class controller name and predicate handling
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/util/kube/kube_suite_test.go
  pkg/util/kube/predicates.go
  pkg/util/kube/predicates_test.go
Labels: size/XL

#1044 🌱 Introduce capability for VM AF/Anti-AF Placement Policies
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
Labels: size/M

#1050 ✨ Introduce VirtualMachineGroupPublishRequest API
  api/v1alpha4/virtualmachinegroup_publishrequest_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegrouppublishrequests.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/virtualmachinegrouppublishrequest/virtualmachinegrouppublishrequest_controller.go
  controllers/virtualmachinegrouppublishrequest/virtualmachinegrouppublishrequest_controller_suite_test.go
  pkg/context/virtualmachinegrouppublishrequest_context.go
Labels: size/L

#1047 🌱 Add VMSnapshot Validation Webhook logic
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_intg_test.go
  webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go
Labels: size/L

#1051 vm: add snapshot validations
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#1055 🌱 VMICache location / disk promotion ignores snapshots & waits on guest customization
  api/v1alpha3/virtualmachineimagecache_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachineimagecache_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineimagecaches.yaml
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/util/vsphere/library/item_cache.go
  pkg/util/vsphere/library/item_cache_test.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go
Labels: size/XL

#1058 ✨ Set VM placement result from group if applicable
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#1062 🌱 Remove stale owner ref when group name changes
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinegroup_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  pkg/util/vmopv1/owner_refs.go
  pkg/util/vmopv1/owner_refs_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_intg_test.go
Labels: size/L

#1066 ✨ Basic Group Placement support
  pkg/providers/vsphere/placement/cluster_placement.go
  pkg/providers/vsphere/placement/group_placement.go
  pkg/providers/vsphere/placement/zone_placement.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/storage/storage.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/vm_provider_vm_group.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_vm_group.go
  pkg/providers/vsphere/vmprovider_vm_group_test.go
  pkg/providers/vsphere/vsphere_suite_test.go
Labels: size/XL
