Repository vmware-tanzu/vm-operator, pull requests merged in 2025-06, with the labels that each got.

#984 ✨ Report disk capacity for usage
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_storage_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  docs/concepts/workloads/vm.md
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  test/builder/test_suite.go
Labels: size/XXL

#954 Introduce VirtualMachineGroup API and controller for reconciling members
  api/v1alpha4/virtualmachinegroup_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/virtualmachine/controllers.go
  controllers/virtualmachine/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachine/virtualmachinegroup/virtualmachinegroup_controller_suite_test.go
  controllers/virtualmachine/virtualmachinegroup/virtualmachinegroup_controller_test.go
  docs/ref/api/v1alpha4.md
  pkg/context/virtualmachinegroup_context.go
  test/builder/fake.go
Labels: size/XL

#944 🌱 Allow 'default' for routes To value
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha4/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/network/netplan_test.go
  pkg/providers/vsphere/network/network_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M

#973 ✨Introduce VM Affinity/Anti-Affinity Spec API
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_affinity_types.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha4.md
Labels: size/XL

#980 ✨ Refactor VM reconcile logic order
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  go.mod
  pkg/constants/constants.go
  pkg/context/virtualmachine_context.go
  pkg/errors/requeue_error.go
  pkg/providers/vsphere/resources/vm.go
  pkg/providers/vsphere/session/session.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
  pkg/providers/vsphere/virtualmachine/cdrom.go
  pkg/providers/vsphere/virtualmachine/cdrom_test.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/virtualmachine/delete_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep_test.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vsphere_suite_test.go
  pkg/util/vsphere/vm/hardware_version.go
  pkg/vmconfig/crypto/crypto_reconciler.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go
  test/builder/dummies.go
  test/builder/test_suite.go
Labels: size/XXL

#997 🌱 Verify unfocus
  .github/workflows/ci.yml
  Makefile
  hack/verify-unfocus.sh
Labels: size/M

#976 ✨ Introduce VirtualMachineSnapshot API
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinesnapshot_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesnapshots.yaml
  docs/ref/api/v1alpha4.md
Labels: size/L

#992 ✨ Skip delete platform resource annotation
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
  controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
  pkg/constants/constants.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#998 🐛 Fix issue adding cd-roms to powering on VMs
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/M

#1000 🐛 Dependabot golang.org/x/net
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M

#1004 🌱 Add spec.groupName to VM API
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha4.md
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#1002 Graceful VM dir cleanup / crypto+linked
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/vmlifecycle/create.go
  pkg/providers/vsphere/vmlifecycle/create_fastdeploy.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/M

#995 ✨ VirtualMachineGroup Power State Reconciliation
  config/webhook/manifests.yaml
  controllers/virtualmachine/virtualmachinegroup/virtualmachinegroup_controller.go
  pkg/constants/constants.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_suite_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_intg_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_suite_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_unit_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_intg_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_suite_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go
  webhooks/virtualmachinegroup/webhooks.go
  webhooks/webhooks.go
Labels: size/XXL

#1011 ✨ Add NextForcePowerStateSyncTime and BootOrder in VM Group
  api/v1alpha4/virtualmachinegroup_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
  controllers/controllers.go
  controllers/virtualmachine/controllers.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_suite_test.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
  docs/ref/api/v1alpha4.md
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_intg_test.go
  webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_unit_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_intg_test.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go
Labels: size/XL

#1019 🐛 Relax VM Group webhook to allow power state changes
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
  webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go
Labels: size/L

#1017 🐛 Fix PCI DVX devs on update
  pkg/util/resize/backings.go
  pkg/util/resize/backings_test.go
  pkg/util/resize/configspec_pci_devcies_test.go
  pkg/util/resize/configspec_pci_devices.go
Labels: size/L

#1015 :sparkles: Handle VM Class instances during VM class reconcile
  api/v1alpha4/virtualmachineclassinstance_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineclassinstances.yaml
  config/rbac/role.yaml
  controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
  controllers/virtualmachineclass/virtualmachineclass_controller.go
  controllers/virtualmachineclass/virtualmachineclass_controller_intg_test.go
  controllers/virtualmachineclass/virtualmachineclass_controller_suite_test.go
  controllers/virtualmachineclass/virtualmachineclass_controller_unit_test.go
  pkg/constants/constants.go
  test/builder/fake.go
Labels: size/L

#1020 🐛 Disable schema not yet upgrade VM validation checks
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/M

#1022 🌱 Consolidate reconcile member and add tests in VM Group controller
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinegroup_types.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
Labels: size/XL

#1027 :seedling: Drop the Status sub-resource from payloads during backup
  pkg/providers/vsphere/virtualmachine/backup.go
Labels: size/S

#1023 :seedling: Mutating and validating webhook changes for spec.class and spec.className
  pkg/util/vmopv1/resize.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL

#1036 🌱 Grab image tag from container image for deploy-wcp
  hack/deploy-wcp.sh
Labels: size/S

#1033 🌱 Update v1a1 network interfaces version up-convert
  api/v1alpha1/virtualmachine_conversion.go
Labels: size/S
