Repository vmware-tanzu/vm-operator, pull requests merged in 2025-02, with the labels that each got.

#788 :bug: Ignore IPv6 Route advertisement in case DHCPv6 wasn't requested
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/network/netplan_test.go
Labels: size/XS, cla-not-required

#876 🐛 Fix CRD capability controller numExit races
  controllers/infra/capability/crd/crd_capability_controller_test.go
Labels: size/XS

#882 🌱 Add VMICache to infra YAML
  config/crd/kustomization.yaml
Labels: size/XS

#884 🌱 Return taskInfo from successful VM Reconfigure task
  pkg/providers/vsphere/resources/vm.go
Labels: size/XS

#879 🌱 Simplify with controller-runtime IgnoreNotFound() helper
  controllers/infra/configmap/infra_configmap_controller.go
  controllers/virtualmachine/volume/volume_controller.go
Labels: size/S

#883 🐛 Fix duplicate append of Image.Status fields
  pkg/providers/vsphere/contentlibrary/content_library_utils.go
  pkg/providers/vsphere/contentlibrary/content_library_utils_test.go
Labels: size/S

#886 Always load the infra/zone controller
  controllers/infra/controllers.go
Labels: size/XS

#887 🌱 Go 1.23.6
  .github/workflows/ci.yml
Labels: size/S

#888 🌱 (x-port vc-9.0.0) Go 1.23.6
  .github/workflows/ci.yml
Labels: size/S

#889 🌱 (x-port vc-9.0.0) Increase CPU and mem limit for controller-manager pod
  config/wcp/vmoperator/cpu_resources_patch.yaml
Labels: size/XS

#890 🐛 (x-port vc-9.0.0) Always load the infra/zone controller
  controllers/infra/controllers.go
Labels: size/XS

#892 :seedling: Include UUID of disk backing in disk backup (#864)
  pkg/backup/api/backup_types.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/virtualmachine/backup_test.go
Labels: size/S

#891 (x-port vc-9.0.0) 🐛 Handle invalid VC Session in GetVirtualMachine()
  pkg/providers/vsphere/vcenter/getvm.go
  pkg/providers/vsphere/vcenter/getvm_test.go
  pkg/providers/vsphere/vmprovider.go
Labels: size/L

#880 🌱 Remove IsVirtualMachineSetResourcePolicyReady()
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/vmprovider_resourcepolicy.go
  pkg/providers/vsphere/vmprovider_resourcepolicy_test.go
Labels: size/L

#870 🌱 Do not requeue VMIC for empty Spec fields
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  pkg/errors/requeue_error.go
  pkg/errors/requeue_error_test.go
Labels: size/L

#839 🌱 Enable all errorlint checks
  .golangci.yml
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  pkg/providers/vsphere/contentlibrary/content_library_provider.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/vmlifecycle/bootstrap.go
  pkg/util/kube/spq/spq.go
  pkg/util/vsphere/vm/hardware_version_test.go
  pkg/util/vsphere/vm/power_state.go
  pkg/util/vsphere/watcher/watcher_test.go
  test/testutil/util.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#881 🌱 Do deployment rollout when capabilities change
  .golangci.yml
  config/default/manager_pod_info_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/local/vmoperator/local_env_var_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/replacements/kustomization.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  controllers/infra/capability/configmap/configmap_capability_controller.go
  controllers/infra/capability/configmap/configmap_capability_controller_suite_test.go
  controllers/infra/capability/configmap/configmap_capability_controller_test.go
  controllers/infra/capability/crd/crd_capability_controller.go
  controllers/infra/capability/crd/crd_capability_controller_suite_test.go
  controllers/infra/capability/crd/crd_capability_controller_test.go
  controllers/infra/capability/exit/exit.go
  main.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/constants/constants.go
  pkg/exit/exit.go
  pkg/exit/exit_suite_test.go
  pkg/exit/exit_test.go
  pkg/manager/manager.go
Labels: size/XXL

#895 🌱 Use UnsafeDisableDeepCopy when possible
  controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
Labels: size/S

#896 🌱 Only reconcile connected VMs
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/vsphere/watcher/watcher.go
Labels: size/M

#898 🌱 Fix broken ubuntu image link in docs
  docs/concepts/images/vm-image.md
Labels: size/XS

#877 🐛 Avoid needlessly VC client logout when creds haven't changed
  controllers/contentlibrary/utils/controller_builder_test.go
  controllers/infra/secret/infra_secret_controller.go
  controllers/infra/secret/infra_secret_controller_intg_test.go
  controllers/infra/secret/infra_secret_controller_suite_test.go
  pkg/config/config.go
  pkg/config/default.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/constants/constants.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/client/client.go
  pkg/providers/vsphere/client/client_test.go
  pkg/providers/vsphere/config/config.go
  pkg/providers/vsphere/config/config_test.go
  pkg/providers/vsphere/credentials/credentials.go
  pkg/providers/vsphere/credentials/credentials_test.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
  test/builder/vcsim_test_context.go
Labels: size/XL

#899 🌱 Do not delete non-connected VMs
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/virtualmachine/delete_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#900 🌱 Remove Folder and ResourcePool from VC config
  pkg/providers/vsphere/config/config.go
  pkg/providers/vsphere/config/config_test.go
Labels: size/S

#901 [x-port 9.0] 🌱 Do not update/delete non-connected VMs
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  pkg/errors/errors_suite_test.go
  pkg/errors/requeue_error.go
  pkg/errors/requeue_error_test.go
  pkg/providers/vsphere/virtualmachine/delete.go
  pkg/providers/vsphere/virtualmachine/delete_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/vsphere/watcher/watcher.go
Labels: size/L

#894 🐛 Use sentinel not found error in GetVirtualMachine()
  pkg/providers/vsphere/vcenter/getvm.go
Labels: size/S

#905 :bug: Allow non-class changes to VM spec for classless VMs
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/S

#907 🌱 VM validation validateCdrom() does not need to be pointer receiver
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/XS

#908 🌱 Fix expected error message in VM network validation
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XS

#906 🌱 Remove old network import alias in provider
  pkg/providers/vsphere/session/session_vm_update.go
Labels: size/S
