Repository vmware-tanzu/vm-operator, pull requests merged in 2025-09, with the labels that each got.

#1120 🌱 Support BYOK capability
  pkg/config/capabilities/capabilities.go
Labels: size/XS

#1147 🌱 Relocate VirtualMachineOrGroup interface and fix VM/VMG get functions receivers
  api/v1alpha2/virtualmachine_types.go
  api/v1alpha2/virtualmachinegroup_types.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/virtualmachinegroup_types.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinegroup_types.go
  api/v1alpha5/virtualmachine_types.go
  api/v1alpha5/virtualmachinegroup_types.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  pkg/util/vmopv1/owner_refs.go
  pkg/util/vmopv1/owner_refs_test.go
  pkg/util/vmopv1/vmgroup.go
  pkg/util/vmopv1/vmgroup_test.go
Labels: size/XL

#1117 ✨ Add MacAddress to VM InterfaceSpec
  api/test/v1alpha1/virtualmachine_conversion_test.go
  api/test/v1alpha2/virtualmachine_conversion_test.go
  api/test/v1alpha3/virtualmachine_conversion_test.go
  api/test/v1alpha4/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_network_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha5/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  go.mod
  go.sum
  pkg/providers/vsphere/network/devices.go
  pkg/providers/vsphere/network/devices_test.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/network/reconcile.go
  pkg/providers/vsphere/session/session_vm_update.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL

#1143 🌱 Verify if a VM Template is Associated with a VM Publish Request
  api/v1alpha5/virtualmachinepublishrequest_types.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  pkg/providers/vsphere/virtualmachine/publish.go
  pkg/providers/vsphere/vmlifecycle/create_fastdeploy.go
Labels: size/M

#1150 :bug: Add flag to OVF CreateSpec to preserve ExtraConfig
  pkg/providers/vsphere/virtualmachine/publish.go
Labels: size/XS

#1130 ✨ Convert VM in extra config of snapshot to newest APIVersion
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
  pkg/providers/vsphere/virtualmachine/snapshot_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/kube/vmsnapshot.go
  pkg/util/kube/vmsnapshot_test.go
  test/builder/dummies.go
Labels: size/L

#1155 🐛 Bump govmomi to 3676bbffada5 and fix related failures
  go.mod
  go.sum
  pkg/providers/vsphere/placement/cluster_placement.go
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/M

#1140 🌱 Emit a condition for a failed snapshot revert operation
  api/v1alpha5/virtualmachine_types.go
  pkg/constants/constants.go
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
Labels: size/L

#1146 🌱 Reverts a VM to the same power state as that of the snapshot
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/dummies.go
Labels: size/L

#1160 🌱 Add PVC WFFC capability
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  pkg/config/capabilities/capabilities.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/config.go
Labels: size/M

#1157 🐛 Return no requeue error when group member is NotFound or NotMember
  controllers/virtualmachinegroup/virtualmachinegroup_controller.go
  controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
Labels: size/M

#1151 🌱 Update WFFC PVCs earlier in volume reconciliation
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_intg_test.go
Labels: size/M

#1153 🐛 Do not unset NetOP network name with default network
  pkg/providers/vsphere/network/network.go
Labels: size/XS

#1163 :bug: Fix issue where publish requests to inventory-backed CL was not marked complete
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  pkg/context/virtualmachinepublishrequest_context.go
  pkg/providers/fake/fake_vm_provider.go
  pkg/providers/vm_provider_interface.go
  pkg/providers/vsphere/virtualmachine/publish.go
  pkg/providers/vsphere/vmprovider.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/XL

#1180 🌱 Add Capability for shared disks
  pkg/config/capabilities/capabilities.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/config.go
Labels: size/M

#1171 :seedling: Support explicit zone specification from group members
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#1169 🌱Refactor some snapshot related code
  controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
  pkg/providers/vsphere/virtualmachine/snapshot.go
  pkg/providers/vsphere/virtualmachine/snapshot_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_snapshot.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/kube/vmsnapshot.go
  pkg/util/kube/vmsnapshot_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vmopv1/vm_test.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go
Labels: size/XL

#1191 :seedling: Bump up golang version to handle CVE GO-2025-3956
  go.mod
Labels: size/XS

#1182 🌱 Remove VM Operator managed labels in VM placement
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
  pkg/util/kube/label.go
  pkg/util/kube/label_test.go
  pkg/util/kube/vm.go
  pkg/util/kube/vm_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL

#1158 :seedling: Remove all unused fields and types from v1alpha3 and v1alpha4
  api/test/v1alpha3/conversion_test.go
  api/test/v1alpha4/conversion_test.go
  api/test/v1alpha4/virtualmachine_conversion_test.go
  api/v1alpha3/virtualmachineimagecache_conversion.go
  api/v1alpha3/virtualmachineimagecache_types.go
  api/v1alpha3/virtualmachinereplicaset_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/virtualmachine_bootstrap_types.go
  api/v1alpha4/virtualmachine_conversion.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/virtualmachinegroup_publishrequest_types.go
  api/v1alpha4/virtualmachineimagecache_conversion.go
  api/v1alpha4/virtualmachineimagecache_types.go
  api/v1alpha4/virtualmachinereplicaset_types.go
  api/v1alpha4/virtualmachinesnapshot_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinegrouppublishrequests.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachineimagecaches.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachinesnapshots.yaml
  webhooks/conversion/v1alpha3/webhooks.go
  webhooks/conversion/v1alpha4/webhooks.go
Labels: size/XXL

#1192 🌱 Add capability for VC_GuestCustomizationVCDParity
  pkg/config/capabilities/capabilities.go
  pkg/config/capabilities/capabilities_test.go
  pkg/config/config.go
Labels: size/M

#1179 🌱Add mutating webhook for rac and wsfc workload
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L

#1197 :bug: Fix typo in cloud-init docs
  docs/tutorials/deploy-vm/cloudinit.md
Labels: size/XS

#1201 [x-port] Remove caBundle from conversion webhook defs
  config/crd/patches/webhook_in_clustervirtualmachineimages.yaml
  config/crd/patches/webhook_in_virtualmachineclasses.yaml
  config/crd/patches/webhook_in_virtualmachineimages.yaml
  config/crd/patches/webhook_in_virtualmachinepublishrequests.yaml
  config/crd/patches/webhook_in_virtualmachines.yaml
  config/crd/patches/webhook_in_virtualmachineservices.yaml
  config/crd/patches/webhook_in_virtualmachinesetresourcepolicies.yaml
  config/crd/patches/webhook_in_virtualmachinewebconsolerequests.yaml
Labels: size/S

#1210 Handle publishing of encrypted VMs for inventory-backed ContentLibraries
  api/v1alpha5/virtualmachinepublishrequest_types.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
  pkg/providers/vsphere/virtualmachine/extraconfig.go
  pkg/providers/vsphere/virtualmachine/extraconfig_test.go
  pkg/providers/vsphere/virtualmachine/publish.go
  pkg/providers/vsphere/virtualmachine/publish_test.go
  pkg/providers/vsphere/vmprovider_vm.go
Labels: size/L

#1205 🌱 Allow VM Spec.Bootstrap to be mutable
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L
