Repository vmware-tanzu/vm-operator, pull requests merged in 2025-05, with the labels that each got.

#937 ✨ Nuke the old session based class VM updating
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#952 ✨ Support for Cloud-init wait-on-network in v1alpha4
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_bootstrap_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/ref/api/v1alpha4.md
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
Labels: size/L

#949 ✨ FastDeploy: Add DiskPromotion API and reconciler
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
  go.mod
  go.sum
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler_suite_test.go
  pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go
Labels: size/XL

#939 ✨ Add option to not configure gateway on interfaces
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha4/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/network/gosc.go
  pkg/providers/vsphere/network/gosc_test.go
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/network/netplan_test.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#959 :seedling: Cleanup image check from storage quota validator create
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
Labels: size/S

#951 ✨ Handle network interfaces changes during VM power on
  pkg/providers/vsphere/network/gosc_test.go
  pkg/providers/vsphere/network/list_interfaces.go
  pkg/providers/vsphere/network/list_interfaces_test.go
  pkg/providers/vsphere/network/netplan_test.go
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/resize/backings.go
  pkg/util/resize/backings_test.go
  test/builder/vcsim_test_context.go
Labels: size/XXL

#960 🌱 Move utilconversion test helpers into pkg
  api/utilconversion/fuzztests/conversion_fuzz.go
  api/v1alpha1/conversion_test.go
  api/v1alpha2/conversion_test.go
  api/v1alpha3/conversion_test.go
Labels: size/L

#958 api: Rename VirtualMachineImageCache Disk -> File
  api/v1alpha3/virtualmachineimagecache_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/virtualmachineimagecache_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachineimagecaches.yaml
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
  docs/ref/api/v1alpha3.md
  docs/ref/api/v1alpha4.md
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/M

#962 Add PromoteDisksMode "Disabled" to kubebuilder validation enum
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/XS

#963 :bug: Storage Quota validator should return the sum of all disk capacities in image status
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
Labels: size/L

#965 🌱 Report VM status.hostName
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/virtualmachine_types.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_network_types.go
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  controllers/virtualmachinewebconsolerequest/v1alpha1/patch/patch_test.go
  hack/deploy-local.sh
  pkg/patch/patch_test.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
Labels: size/L

#972 🌱 Add Capability for VM Groups
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
Labels: size/M

#971 Make VM Route Metric field optional
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha4/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/network/netplan_test.go
Labels: size/M

#969 🌱 Initialize VM interface Network reference on update
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L

#966 🌱 Move PCI passthrough comparison into resize
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/util/resize/backings.go
  pkg/util/resize/backings_test.go
  pkg/util/resize/configspec_devices.go
  pkg/util/resize/configspec_pci_devcies_test.go
  pkg/util/resize/configspec_pci_devices.go
Labels: size/XL

#967 :sparkles: Define new `VirtualMachineBootOptions` API
  api/v1alpha1/virtualmachine_conversion.go
  api/v1alpha1/virtualmachine_conversion_test.go
  api/v1alpha1/zz_generated.conversion.go
  api/v1alpha2/virtualmachine_conversion.go
  api/v1alpha2/virtualmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/virtualmachine_conversion.go
  api/v1alpha3/virtualmachine_conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/virtualmachine_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/L

#977 📖 Remove stale comment about network interface spec Addresses field
  api/v1alpha2/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha4/virtualmachine_network_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Labels: size/S

#978 🌱 Support skip-validation annotation
  pkg/builder/constants.go
  pkg/builder/validating_webhook.go
  pkg/builder/validating_webhook_test.go
  pkg/constants/constants.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
  webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_intg_test.go
Labels: size/L

#974 🌱 Ensure network interface provider ref is set even with no default annotation
  webhooks/virtualmachine/mutation/virtualmachine_mutator.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/M

#982 📖 Update mkdocs deps used to build docs
  docs/requirements.txt
Labels: size/S

#981 📖 Update link to GuestOS IDs
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha4/virtualmachine_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
  docs/concepts/workloads/vm.md
  docs/ref/api/v1alpha1.md
  docs/ref/api/v1alpha2.md
  docs/ref/api/v1alpha3.md
  docs/ref/api/v1alpha4.md
  docs/tutorials/deploy-vm/iso.md
Labels: size/S

#968 Add Capability for Immutable VM Classes
  pkg/config/capabilities/capabilities_test.go
  pkg/config/capabilities/capabilties.go
  pkg/config/config.go
Labels: size/M

#983 🐛 Only set Netplan MTU if a positive value
  pkg/providers/vsphere/network/netplan.go
  pkg/providers/vsphere/network/netplan_test.go
Labels: size/S

#942 🌱 Use OpaqueNetwork backing for NSX for VM create
  pkg/providers/vsphere/network/network.go
  pkg/providers/vsphere/network/network_test.go
  pkg/providers/vsphere/network/nsxt.go
  pkg/providers/vsphere/network/nsxt_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm2_test.go
Labels: size/L

#986 deps: Bump govmomi to include CreateSCSIController fix
  go.mod
  go.sum
Labels: size/XS
