Repository vmware-tanzu/vm-operator, pull requests merged in 2025-03, with the labels that each got.

#893 🌱 Add resize MatchVirtualDevice placeholder
  pkg/util/resize/configspec_devices.go
  pkg/util/resize/configspec_devices_test.go
  pkg/util/resize/configspec_pci_devices.go
  pkg/util/resize/configspec_test.go
Labels: size/XL

#904 🌱 Remove FSS ISO Support
  config/local/vmoperator/local_env_var_patch.yaml
  config/wcp/vmoperator/manager_env_var_patch.yaml
  pkg/config/config.go
  pkg/config/env.go
  pkg/config/env/env.go
  pkg/config/env_test.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  test/builder/dummies.go
  test/builder/vcsim_test_context.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L

#897 🌱 Add sub-modules in go lint and fix reported issues
  .golangci.yml
  Makefile
  api/utilconversion/conversion_fuzz.go
  api/v1alpha1/conversion_test.go
  api/v1alpha1/virtualmachineimage_conversion.go
  api/v1alpha2/doc.go
  api/v1alpha2/sysprep/conversion/v1alpha2/sysprep_conversion.go
  api/v1alpha2/sysprep/conversion/v1alpha4/sysprep_conversion.go
  api/v1alpha2/sysprep/sysprep.go
  api/v1alpha2/virtualmachine_readiness_types.go
  api/v1alpha3/cloudinit/cloudconfig.go
  api/v1alpha3/common/conversion/v1alpha3/common_conversion.go
  api/v1alpha3/common/conversion/v1alpha4/common_conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/sysprep/sysprep.go
  api/v1alpha3/virtualmachine_bootstrap_types.go
  api/v1alpha3/virtualmachine_network_types.go
  api/v1alpha3/virtualmachine_readiness_types.go
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha3/virtualmachineimage_types.go
  api/v1alpha3/virtualmachineimagecache_conversion.go
  api/v1alpha3/virtualmachineimagecache_types.go
  api/v1alpha3/virtualmachinereplicaset_types.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/sysprep/sysprep.go
  api/v1alpha4/virtualmachine_readiness_types.go
  api/v1alpha4/virtualmachineimagecache_types.go
  api/v1alpha4/virtualmachinereplicaset_types.go
  config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
  docs/ref/api/v1alpha3.md
  docs/ref/api/v1alpha4.md
Labels: size/L

#885 ⚠️ Remove UpdateConfigSpecFirmware()
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/session/session_vm_update_test.go
  pkg/providers/vsphere/virtualmachine/configspec.go
Labels: size/M

#911 Update vcsim usage with simulator.Map var refactor
  go.mod
  go.sum
  pkg/providers/vsphere/client/client_test.go
  pkg/providers/vsphere/placement/zone_placement_test.go
  pkg/providers/vsphere/virtualmachine/delete_test.go
  pkg/providers/vsphere/vmprovider_vm_test.go
  pkg/util/vsphere/client/client_test.go
  test/builder/vcsim_test_context.go
Labels: size/M, cla-not-required

#913 :bug: Do not patch a zone with finalizer if it is being deleted
  pkg/util/vsphere/watcher/watcher.go
  pkg/util/vsphere/watcher/watcher_context.go
  services/vm-watcher/vm_watcher_service.go
  services/vm-watcher/vm_watcher_service_test.go
Labels: size/L, cla-not-required

#914 🌱 Use Gomega asserts in Eventually/Consistently checks Volume integration tests
  controllers/virtualmachine/volume/volume_controller_intg_test.go
Labels: size/L, cla-not-required

#915 📖 Fix var name in description of backup condition reasons
  api/v1alpha3/virtualmachine_types.go
  api/v1alpha4/virtualmachine_types.go
Labels: size/XS, cla-not-required

#912 ✨ Support PVCs with WFFC StorageClass
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_intg_test.go
  controllers/virtualmachine/volume/volume_controller_suite_test.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/XL, cla-not-required

#916 🐛 Handle resize for VMs that were classless
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/vmopv1/resize.go
  pkg/util/vmopv1/resize_test.go
  webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
Labels: size/L, cla-not-required

#918 🌱 Golang 1.24.1 / Golangci-lint 1.64.7
  .github/workflows/ci.yml
  .golangci.yml
  Makefile
  controllers/virtualmachine/volume/volume_controller.go
  controllers/virtualmachine/volume/volume_controller_unit_test.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  controllers/virtualmachineservice/virtualmachineservice_controller.go
  go.mod
  hack/test.sh
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/providers/vsphere/network/gosc.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/vcenter/cluster.go
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/devices.go
  pkg/providers/vsphere/vmlifecycle/bootstrap_templatedata.go
  pkg/providers/vsphere/vmprovider_vm_resize_test.go
  pkg/util/configspec.go
  pkg/util/kube/predicates_test.go
  pkg/util/resize/configspec.go
  pkg/util/vmopv1/resize_test.go
  pkg/util/vmopv1/vm.go
  pkg/util/vsphere/vm/hardware_version.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
Labels: size/L, cla-not-required

#902 🌱 Defaults for ConfigSpec CPU/mem alloc
  pkg/providers/vsphere/virtualmachine/configspec.go
  pkg/providers/vsphere/virtualmachine/configspec_test.go
Labels: size/M

#917 🐛 (x-port vc-9.0.0) Do not patch a zone with finalizer if it is being deleted
  pkg/util/vsphere/watcher/watcher.go
  pkg/util/vsphere/watcher/watcher_context.go
  services/vm-watcher/vm_watcher_service.go
  services/vm-watcher/vm_watcher_service_test.go
Labels: size/L, cla-not-required

#922 🌱 Fix new go vet non const printf warnings
  controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
  controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
  controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/getter.go
  controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/merge.go
  hack/test.sh
  pkg/conditions/conditions.go
  pkg/conditions/getter.go
  pkg/conditions/merge.go
  pkg/conditions/setter.go
  pkg/conditions/setter_test.go
  pkg/prober/worker/readiness_worker.go
  pkg/providers/vsphere/session/session_vm_update.go
  pkg/providers/vsphere/virtualmachine/backup.go
  pkg/providers/vsphere/vmlifecycle/update_status.go
  pkg/providers/vsphere/vmlifecycle/update_status_test.go
  pkg/providers/vsphere/vmprovider_vm.go
  pkg/providers/vsphere/vmprovider_vm_utils.go
  pkg/providers/vsphere/vmprovider_vm_utils_test.go
  pkg/vmconfig/crypto/crypto_reconciler.go
  pkg/vmconfig/crypto/crypto_reconciler_pre.go
Labels: size/L, cla-not-required

#920 🐛 Determine NS associated StorageClass only with Policy ID
  controllers/storagepolicyquota/storagepolicyquota_controller.go
  pkg/util/kube/spq/spq.go
  pkg/util/kube/spq/spq_suite_test.go
  pkg/util/kube/spq/spq_test.go
  test/builder/dummies.go
  webhooks/virtualmachine/validation/virtualmachine_validator.go
  webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Labels: size/L, cla-not-required
